### ISSUE TITLE
TypeError: 无法调用null的方法

### ISSUE THREAD

**Issue by Rsweater** [lolisaikou/LazyStudy#1]
你的手机型号：
honor 10
你的安卓版本：
andorid 10
错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/，然后把图片链接贴在这里）
https://ftp.bmp.ovh/imgs/2020/06/575e5a9f67451a28.jpg
![Screenshot_20200620_213405_cn xuexi android](https://user-images.githubusercontent.com/49091147/85203300-5181e400-b33f-11ea-8b27-fbc28ff74deb.jpg)

错误描述：
还有文章剩余时长显示NaN

**Comment by lolisaikou** [comment]
啊这个是正常的
证明你今天浏览部分的分学够了

**Comment by lolisaikou** [comment]
那个报错不影响
还有我修复了一些小问题，但是不方便改版本号了。所以你先[更新](https://github.com/lolisaikou/LazyStudy/releases/tag/v2.5.8)程序吧，记得备份一下题库哦。然后更新完了恢复就行
没什么问题的话就回复我一下，我关一下issue

**Comment by Rsweater** [comment]
> 那个报错不影响
> 还有我修复了一些小问题，但是不方便改版本号了。所以你先[更新](https://github.com/lolisaikou/LazyStudy/releases/tag/v2.5.8)程序吧，记得备份一下题库哦。然后更新完了恢复就行
> 没什么问题的话就回复我一下，我关一下issue
没了

**Comment by Rsweater** [comment]
> > 那个报错不影响
> > 还有我修复了一些小问题，但是不方便改版本号了。所以你先[更新](https://github.com/lolisaikou/LazyStudy/releases/tag/v2.5.8)程序吧，记得备份一下题库哦。然后更新完了恢复就行
> > 没什么问题的话就回复我一下，我关一下issue
> > 没了



> > 那个报错不影响
> > 还有我修复了一些小问题，但是不方便改版本号了。所以你先[更新](https://github.com/lolisaikou/LazyStudy/releases/tag/v2.5.8)程序吧，记得备份一下题库哦。然后更新完了恢复就行
> > 没什么问题的话就回复我一下，我关一下issue
> > 没了



> 那个报错不影响
> 还有我修复了一些小问题，但是不方便改版本号了。所以你先[更新](https://github.com/lolisaikou/LazyStudy/releases/tag/v2.5.8)程序吧，记得备份一下题库哦。然后更新完了恢复就行
> 没什么问题的话就回复我一下，我关一下issue

没了，感谢

**Comment by Rsweater** [comment]
> 那个报错不影响
> 还有我修复了一些小问题，但是不方便改版本号了。所以你先[更新](https://github.com/lolisaikou/LazyStudy/releases/tag/v2.5.8)程序吧，记得备份一下题库哦。然后更新完了恢复就行
> 没什么问题的话就回复我一下，我关一下issue

没了  感谢
