### ISSUE TITLE
想问一下学习强国需要什么版本？

### ISSUE THREAD

**Issue by LINGJULIDEHUIMOU** [lolisaikou/LazyStudy#10]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by lolisaikou** [comment]
应用商店下载最新的版本就行

**Comment by jw8013** [comment]
> 应用商店下载最新的版本就行

v2.6.3 解析软件包出现错误
v2.6.3_44P版本正常
