### ISSUE TITLE
用008的代码就不会有问题

### ISSUE THREAD

**Issue by lnxcyq** [lolisaikou/LazyStudy#105]
争上游和对战差不多。速度问题怎么解决，如果中间延时长，答题就慢，但是稳定些。如果延时短一点，我根据挑战答题写的代码就容易出错。（期待字形题的解决方案）

_Originally posted by @Lee-20 in https://github.com/lolisaikou/LazyStudy/issues/90#issuecomment-711210902_

**Comment by Ivan-cn** [comment]
要设为500ms ，设太短会卡住
