### ISSUE TITLE
一直出现等待加载 。用不起了 后面发现是 qingguo 软件更新了更新到2.17.1了

### ISSUE THREAD

**Issue by guardiangell** [lolisaikou/LazyStudy#106]
你的手机型号：M30

你的安卓版本：10

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：
一直出现等待加载，无法使用

**Comment by 85524365** [comment]
安卓8也卡住了，期待大神出手了

**Comment by ID-JRL** [comment]
同样的问题  希望作者更新

**Comment by Kiss-YuJiu** [comment]
> 同样的问题 希望作者更新

把听新闻广播改成听广播就可以了

**Comment by qq272285154** [comment]
> > 同样的问题 希望作者更新
> 
> 把听新闻广播改成听广播就可以了

确实，今天开始加载中，把广播该了OK

**Comment by nishenge** [comment]
> > > 同样的问题 希望作者更新
> > 
> > 
> > 把听新闻广播改成听广播就可以了
> 
> 确实，今天开始加载中，把广播该了OK

请问在哪个文件里改

**Comment by nishenge** [comment]
> > 同样的问题 希望作者更新
> 
> 把听新闻广播改成听广播就可以了

请问在哪个文件里改

**Comment by ID-JRL** [comment]
> > 同样的问题 希望作者更新
> 
> 把听新闻广播改成听广播就可以了

你好，修改完之后获取完积分就不动了。

**Comment by nanmeng-sujin** [comment]
只用修改文字，其他的不要动发自我的华为手机-------- 原始邮件 --------发件人： 没毛的饺子 <notifications@github.com>日期： 2020年11月17日周二 11:33收件人： lolisaikou/LazyStudy <LazyStudy@noreply.github.com>抄送： nanmeng-sujin <169231774@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [lolisaikou/LazyStudy] 一直出现等待加载 。用不起了 后面发现是 qingguo 软件更新了更新到2.17.1了 (#106)





同样的问题 希望作者更新



把听新闻广播改成听广播就可以了



你好，修改完之后获取完积分就不动了。

**Comment by Kiss-YuJiu** [comment]
> > > 同样的问题 希望作者更新
> > 
> > 
> > 把听新闻广播改成听广播就可以了
> 
> 你好，修改完之后获取完积分就不动了。

只修改文字，其他的不要动

**Comment by ID-JRL** [comment]
> > > > 同样的问题 希望作者更新
> > > 
> > > 
> > > 把听新闻广播改成听广播就可以了
> > 
> > 
> > 你好，修改完之后获取完积分就不动了。
> 
> 只修改文字，其他的不要动

您好，我是用记事本打开的，直接一键替换掉的。 但是结果是打开软件之后只获取积分，然后就没动静了。

**Comment by zouyingfeng** [comment]
> > > > > 同样的问题 希望作者更新
> > > > 
> > > > 
> > > > 把听新闻广播改成听广播就可以了
> > > 
> > > 
> > > 你好,修改完之后获取完积分就不动了。
> > 
> > 
> > 只修改文字,其他的不要动
> 
> 您好,我是用记事本打开的,直接一键替换掉的。但是结果是打开软件之后只获取积分,然后就没动静了。

在什么地方进行修改呢？

**Comment by zouyingfeng** [comment]
> > > > 同样的问题 希望作者更新
> > > 
> > > 
> > > 把听新闻广播改成听广播就可以了
> > 
> > 
> > 你好，修改完之后获取完积分就不动了。
> 
> 只修改文字，其他的不要动

改了之后提示错误，js#1233

**Comment by Kiss-YuJiu** [comment]
> > > > > 同样的问题 希望作者更新
> > > > 
> > > > 
> > > > 把听新闻广播改成听广播就可以了
> > > 
> > > 
> > > 你好，修改完之后获取完积分就不动了。
> > 
> > 
> > 只修改文字，其他的不要动
> 
> 改了之后提示错误，js#1233

1233？？？

**Comment by Kiss-YuJiu** [comment]
> > > > > > 同样的问题 希望作者更新
> > > > > 
> > > > > 
> > > > > 把听新闻广播改成听广播就可以了
> > > > 
> > > > 
> > > > 你好,修改完之后获取完积分就不动了。
> > > 
> > > 
> > > 只修改文字,其他的不要动
> > 
> > 
> > 您好,我是用记事本打开的,直接一键替换掉的。但是结果是打开软件之后只获取积分,然后就没动静了。
> 
> 在什么地方进行修改呢？

在这里面xxqg_v3.1.3.js

大约400行处，电台那个，，进行修改

**Comment by arcqiufeng** [comment]
> > > > > > > 同样的问题 希望作者更新
> > > > > > 
> > > > > > 
> > > > > > 把听新闻广播改成听广播就可以了
> > > > > 
> > > > > 
> > > > > 你好,修改完之后获取完积分就不动了。
> > > > 
> > > > 
> > > > 只修改文字,其他的不要动
> > > 
> > > 
> > > 您好,我是用记事本打开的,直接一键替换掉的。但是结果是打开软件之后只获取积分,然后就没动静了。
> > 
> > 
> > 在什么地方进行修改呢？
> 
> 在这里面xxqg_v3.1.3.js
> 
> 大约400行处，电台那个，，进行修改

请问我是安装的apk，在哪里改？

**Comment by Kiss-YuJiu** [comment]
> > > > > > > > 同样的问题 希望作者更新
> > > > > > > 
> > > > > > > 
> > > > > > > 把听新闻广播改成听广播就可以了
> > > > > > 
> > > > > > 
> > > > > > 你好,修改完之后获取完积分就不动了。
> > > > > 
> > > > > 
> > > > > 只修改文字,其他的不要动
> > > > 
> > > > 
> > > > 您好,我是用记事本打开的,直接一键替换掉的。但是结果是打开软件之后只获取积分,然后就没动静了。
> > > 
> > > 
> > > 在什么地方进行修改呢？
> > 
> > 
> > 在这里面xxqg_v3.1.3.js
> > 大约400行处，电台那个，，进行修改
> 
> 请问我是安装的apk，在哪里改？

改不了

**Comment by Kiss-YuJiu** [comment]
自己手动点一下就好了

**Comment by ID-JRL** [comment]
找到解决办法了  如果是使用软件的话 在跳出等待加载的时候 点击一下电台然后在点听广播就行

**Comment by Kiss-YuJiu** [comment]
是的没毛病

**Comment by arcqiufeng** [comment]
> > > > > > > > > 同样的问题 希望作者更新
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 把听新闻广播改成听广播就可以了
> > > > > > > 
> > > > > > > 
> > > > > > > 你好,修改完之后获取完积分就不动了。
> > > > > > 
> > > > > > 
> > > > > > 只修改文字,其他的不要动
> > > > > 
> > > > > 
> > > > > 您好,我是用记事本打开的,直接一键替换掉的。但是结果是打开软件之后只获取积分,然后就没动静了。
> > > > 
> > > > 
> > > > 在什么地方进行修改呢？
> > > 
> > > 
> > > 在这里面xxqg_v3.1.3.js
> > > 大约400行处，电台那个，，进行修改
> > 
> > 
> > 请问我是安装的apk，在哪里改？
> 
> 改不了

请问不用apk，怎么安装使用？你们为什么可以直接修改脚本？

**Comment by lovestudystrongcountry** [comment]
> 自己手动点一下就好了

大佬，这个脚本是不是只能pro8跑啊，4.x免费版的跑不动啊，您是用哪个版本的autojs烦请指教一下

**Comment by Kiss-YuJiu** [comment]
4x也能

**Comment by arcqiufeng** [comment]
> > 自己手动点一下就好了
> 
> 大佬，这个脚本是不是只能pro8跑啊，4.x免费版的跑不动啊，您是用哪个版本的autojs烦请指教一下

我试了4.0.1beta可以跑。终于用起来了。

**Comment by arcqiufeng** [comment]
> > 自己手动点一下就好了
> 
> 大佬，这个脚本是不是只能pro8跑啊，4.x免费版的跑不动啊，您是用哪个版本的autojs烦请指教一下

https://www.lanzous.com/b895913/
密码:abo3

**Comment by arcqiufeng** [comment]
> > > > > > > > > 同样的问题 希望作者更新
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 把听新闻广播改成听广播就可以了
> > > > > > > 
> > > > > > > 
> > > > > > > 你好,修改完之后获取完积分就不动了。
> > > > > > 
> > > > > > 
> > > > > > 只修改文字,其他的不要动
> > > > > 
> > > > > 
> > > > > 您好,我是用记事本打开的,直接一键替换掉的。但是结果是打开软件之后只获取积分,然后就没动静了。
> > > > 
> > > > 
> > > > 在什么地方进行修改呢？
> > > 
> > > 
> > > 在这里面xxqg_v3.1.3.js
> > > 大约400行处，电台那个，，进行修改
> > 
> > 
> > 请问我是安装的apk，在哪里改？
> 
> 改不了

摸索了一个晚上，弄清楚了，现在可以用了。
