### ISSUE TITLE
一直提示   等待加载

### ISSUE THREAD

**Issue by ID-JRL** [lolisaikou/LazyStudy#107]
你的手机型号：   xiaomi mix2

你的安卓版本： 安卓10

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）
https://smartshen.lanzous.com/icLBxigiw4d
错误描述：
   一直提示等待加载   不进行正常操作

**Comment by Sting-12** [comment]
自己跳到广播里面去就好了

**Comment by KB64ba** [comment]
听广播的界面已经修改，把“听新闻广播”改为“听广播”
click("听广播")

**Comment by uid666** [comment]
> 听广播的界面已经修改，把“听新闻广播”改为“听广播”
> click("听广播")

老哥可以把你的xxqghelper3.1.3发一下嘛。

**Comment by KB64ba** [comment]
/**
 * @description: 听“电台”新闻广播函数  (视听学习+视听学习时长)---6+6=12分
 * @param: null
 * @return: null
 */
function listenToRadio()
{
    var f=0;
    console.log("-----------------------------------------------------------");
    delay(2);
    while(!(desc("学习").exists() || desc("工作").exists() || id("home_bottom_tab_button_work").exists())){
        f++;
        console.log("正在等待加载出主页");
        delay(1);
        if(f>2){
            back();
            var f=0;}
        if((desc("学习").exists() || desc("工作").exists() || id("home_bottom_tab_button_work").exists())){
           f=0;
           break;}}
    click("电台");
    delay(2);
    click("听广播");//新版改版界面
    delay(2);
    click("中国之声");
    console.log("正在收听电台广播...");
    delay(2);
    if(!desc("电台").exists()){
        delay(2);
        back();//返回电台界面
        }
    //back();//返回电台界面
}

**Comment by KB64ba** [comment]
仅限2.17版以下

**Comment by lolisaikou** [comment]
已更新
