### ISSUE TITLE
建议阅读文章更改为订阅下面的文章

### ISSUE THREAD

**Issue by aweder** [lolisaikou/LazyStudy#11]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：
![mmexport1595133179859](https://user-images.githubusercontent.com/3031594/87867126-4095b400-c979-11ea-9fe8-b247733e4de9.jpg)

错误描述：

**Comment by lolisaikou** [comment]
我测试一下，最快明天上线

**Comment by lolisaikou** [comment]
![image](https://user-images.githubusercontent.com/32028165/87920401-b8fc9200-caab-11ea-99ab-fd42d12aa7e7.png)
增加了一个按钮可以供选择
为什么只有这两个选项？因为每天都有大量新文章貌似只有这两个地方（如果有别的地方希望大家指出）
总感觉这个功能对刚开始看这个的没用

**Comment by aweder** [comment]
其实文章标题是有个ID的，建议获取文章标题
     //获取当前正在阅读的文章标题
            var currentNewsTitle = ""
            if (textContains("来源").exists()) { // 有时无法获取到 来源
                currentNewsTitle = textContains("来源").findOne().parent().children()[0].text();
            } else if (textContains("作者").exists()) {
                currentNewsTitle = textContains("作者").findOne().parent().children()[0].text();
            } else if (descContains("来源").exists()) {
                currentNewsTitle = descContains("来源").findOne().parent().children()[0].desc();
            } else if (descContains("作者").exists()) {
                currentNewsTitle = descContains("作者").findOne().parent().children()[0].desc();

这段直接改为按ID查然后获取标题下面的那个view找会更准，免得老是找不到标题，如下面代码中加粗部分，标题id为xxqg-article-header这个控件下，只有一个view,则是标题内容
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy index="0" class="hierarchy" rotation="0" width="1080" height="1920">
  <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,1920]" displayed="true">
    <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" resource-id="cn.xuexi.android:id/pllayout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,1920]" displayed="true">
      <android.widget.LinearLayout index="0" package="cn.xuexi.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,1920]" displayed="true">
        <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,1920]" displayed="true">
          <android.widget.LinearLayout index="0" package="cn.xuexi.android" class="android.widget.LinearLayout" text="" resource-id="cn.xuexi.android:id/action_bar_root" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,1920]" displayed="true">
            <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" resource-id="android:id/content" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,1920]" displayed="true">
              <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,1920]" displayed="true">
                <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1920]" displayed="true" />
                <android.widget.FrameLayout index="1" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1920]" displayed="true">
                  <android.widget.LinearLayout index="0" package="cn.xuexi.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1920]" displayed="true">
                    <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                      <android.widget.LinearLayout index="0" package="cn.xuexi.android" class="android.widget.LinearLayout" text="" resource-id="cn.xuexi.android:id/CENTER_LAYOUT_VIEW_ID" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                        <android.view.ViewGroup index="1" package="cn.xuexi.android" class="android.view.ViewGroup" text="" resource-id="cn.xuexi.android:id/CONTENT_LAYER_VIEW_ID" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                          <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                            <android.widget.RelativeLayout index="0" package="cn.xuexi.android" class="android.widget.RelativeLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                              <com.uc.webview.export.WebView index="0" package="cn.xuexi.android" class="com.uc.webview.export.WebView" text="" resource-id="cn.xuexi.android:id/common_webview" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                                <android.webkit.WebView index="0" package="cn.xuexi.android" class="android.webkit.WebView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                                  <android.webkit.WebView index="0" package="cn.xuexi.android" class="android.webkit.WebView" text="90后创业CP：创业是我们想做的事，就一定要做成" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" long-clickable="false" password="false" scrollable="true" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                                    <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                                      <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" resource-id="app" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                                        <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" resource-id="xxqg-article-content" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                                          <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,1831]" displayed="true">
                                            <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,48][1030,272]" displayed="true">
                                              <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,252][1030,264]" displayed="true" />
                                              <android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[374,48][706,188]" displayed="true" />
                                              <android.view.View index="2" package="cn.xuexi.android" class="android.view.View" text="2020 年 07 月 20 日" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,196][1030,234]" displayed="true" />
                                              <android.view.View index="3" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,266][1030,272]" displayed="true" />
                                            </android.view.View>
                                            **<android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="" resource-id="xxqg-article-header" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,270][1030,484]" displayed="true">
                                              <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="90后创业CP：创业是我们想做的事，就一定要做成" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,270][1030,484]" displayed="true" />
                                            </android.view.View>**
                                            <android.view.View index="2" package="cn.xuexi.android" class="android.view.View" text="" resource-id="xxqg-gg-subscribe" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,514][1030,584]" displayed="true">
                                              <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,520][108,578]" displayed="true" />
                                              <android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="中国青年报" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[122,524][876,574]" displayed="true" />
                                              <android.view.View index="2" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[900,520][1030,578]" displayed="true">
                                                <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="已订阅" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[900,520][1030,578]" displayed="true" />
                                              </android.view.View>
                                            </android.view.View>
                                            <android.view.View index="3" package="cn.xuexi.android" class="android.view.View" text="" resource-id="xxqg-article-body" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1831]" displayed="true">
                                              <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" resource-id="image-text-content" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1831]" displayed="true">
                                                <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" resource-id="video_0" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1180]" displayed="true">
                                                  <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1180]" displayed="true">
                                                    <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" resource-id="dplayer-video-wrap" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1180]" displayed="true">
                                                      <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1180]" displayed="true">
                                                        <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1180]" displayed="true">
                                                          <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1180]" displayed="true" />
                                                        </android.view.View>
                                                      </android.view.View>
                                                      <android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,630][1030,1180]" displayed="true" />
                                                    </android.view.View>
                                                    <android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,896][1030,1180]" displayed="true" />
                                                    <android.view.View index="2" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,1060][1030,1180]" displayed="true">
                                                      <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[108,1070][470,1180]" displayed="true">
                                                        <android.widget.Button index="0" package="cn.xuexi.android" class="android.widget.Button" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[108,1070][226,1180]" displayed="true" />
                                                        <android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="0:00" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[234,1100][320,1148]" displayed="true" />
                                                        <android.view.View index="2" package="cn.xuexi.android" class="android.view.View" text=" / " checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[318,1100][362,1148]" displayed="true" />
                                                        <android.view.View index="3" package="cn.xuexi.android" class="android.view.View" text="00:49" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[360,1100][470,1148]" displayed="true" />
                                                      </android.view.View>
                                                      <android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[854,1070][972,1180]" displayed="true">
                                                        <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[854,1070][972,1180]" displayed="true">
                                                          <android.widget.Button index="0" package="cn.xuexi.android" class="android.widget.Button" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[854,1070][972,1180]" displayed="true" />
                                                        </android.view.View>
                                                      </android.view.View>
                                                      <android.view.View index="2" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[108,1046][972,1086]" displayed="true">
                                                        <android.view.View index="0" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[108,1060][972,1072]" displayed="true" />
                                                      </android.view.View>
                                                    </android.view.View>
                                                    <android.view.View index="3" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[108,966][226,1008]" displayed="true" />
                                                  </android.view.View>
                                                </android.view.View>
                                                <android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="“帮创业者上头条”&#10;" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,1236][1030,1300]" displayed="true" />
                                                <android.view.View index="2" package="cn.xuexi.android" class="android.view.View" text="创业者：刘闯、叶雨桐夫妇&#10;" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,1354][1030,1418]" displayed="true" />
                                                <android.view.View index="3" package="cn.xuexi.android" class="android.view.View" text="个人简介：他是27岁的CEO（首席执行官）、二胎奶爸；她是27岁的COO（首席运营官）、二胎妈妈。2011年，考入西北工业大学的他们初次相识。2014年，作为合伙人，他们注册的第六镜科技公司成立。&#10;" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,1474][1030,1720]" displayed="true" />
                                                <android.view.View index="4" package="cn.xuexi.android" class="android.view.View" text="公司名称：西安第六镜网络科技有限公司&#10;" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[50,1774][1030,1831]" displayed="true" />
                                              </android.view.View>
                                            </android.view.View>
                                          </android.view.View>
                                        </android.view.View>
                                      </android.view.View>
                                    </android.view.View>
                                  </android.webkit.WebView>
                                </android.webkit.WebView>
                              </com.uc.webview.export.WebView>
                            </android.widget.RelativeLayout>
                          </android.widget.FrameLayout>
                        </android.view.ViewGroup>
                      </android.widget.LinearLayout>
                      <android.widget.LinearLayout index="1" package="cn.xuexi.android" class="android.widget.LinearLayout" text="" resource-id="cn.xuexi.android:id/TOP_LAYER_VIEW_ID" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,148]" displayed="true">
                        <android.widget.ImageView index="0" package="cn.xuexi.android" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][112,148]" displayed="true" />
                        <android.widget.RelativeLayout index="1" package="cn.xuexi.android" class="android.widget.RelativeLayout" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[952,48][968,148]" displayed="true" />
                        <android.widget.ImageView index="2" package="cn.xuexi.android" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[984,48][1080,148]" displayed="true" />
                      </android.widget.LinearLayout>
                      <android.view.View index="2" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,48][1080,49]" displayed="true" />
                    </android.widget.FrameLayout>
                    <android.view.View index="1" package="cn.xuexi.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,1831][1080,1832]" displayed="true" />
                    <android.widget.LinearLayout index="2" package="cn.xuexi.android" class="android.widget.LinearLayout" text="" resource-id="cn.xuexi.android:id/BOTTOM_LAYER_VIEW_ID" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,1832][1080,1920]" displayed="true">
                      <android.widget.TextView index="0" package="cn.xuexi.android" class="android.widget.TextView" text="欢迎发表你的观点" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[36,1846][780,1906]" displayed="true" />
                      <android.widget.FrameLayout index="1" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[780,1852][888,1900]" displayed="true">
                        <android.widget.FrameLayout index="0" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[820,1852][868,1900]" displayed="true">
                          <android.widget.ImageView index="0" package="cn.xuexi.android" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[820,1852][868,1900]" displayed="true" />
                        </android.widget.FrameLayout>
                      </android.widget.FrameLayout>
                      <android.widget.ImageView index="2" package="cn.xuexi.android" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[888,1852][976,1900]" displayed="true" />
                      <android.widget.ImageView index="3" package="cn.xuexi.android" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[976,1852][1064,1900]" displayed="true" />
                    </android.widget.LinearLayout>
                  </android.widget.LinearLayout>
                </android.widget.FrameLayout>
              </android.widget.FrameLayout>
              <android.widget.FrameLayout index="1" package="cn.xuexi.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,1920]" displayed="true" />
            </android.widget.FrameLayout>
          </android.widget.LinearLayout>
        </android.widget.FrameLayout>
      </android.widget.LinearLayout>
    </android.widget.FrameLayout>
  </android.widget.FrameLayout>
</hierarchy>

**Comment by lolisaikou** [comment]
因为有些功能还需要测试，所以今天还不能更新

**Comment by lolisaikou** [comment]
> 其实文章标题是有个ID的，建议获取文章标题
> //获取当前正在阅读的文章标题
> var currentNewsTitle = ""
> if (textContains("来源").exists()) { // 有时无法获取到 来源
> currentNewsTitle = textContains("来源").findOne().parent().children()[0].text();
> } else if (textContains("作者").exists()) {
> currentNewsTitle = textContains("作者").findOne().parent().children()[0].text();
> } else if (descContains("来源").exists()) {
> currentNewsTitle = descContains("来源").findOne().parent().children()[0].desc();
> } else if (descContains("作者").exists()) {
> currentNewsTitle = descContains("作者").findOne().parent().children()[0].desc();
> 
> 这段直接改为按ID查然后获取标题下面的那个view找会更准，免得老是找不到标题，如下面代码中加粗部分，标题id为xxqg-article-header这个控件下，只有一个view,则是标题内容
> 
> ** **

我发现了已经改过了

**Comment by lolisaikou** [comment]
已更新，可以到[release](https://github.com/lolisaikou/LazyStudy/releases/)页面下载

**Comment by Muyanglaw** [comment]
厉害了，刚准备反馈下这个问题，没想到今天上来就看到解决了，辛苦了
