### ISSUE TITLE
大神，请问文章和视频的浏览时间是随机的还是固定的，感嗯感谢

### ISSUE THREAD

**Issue by 85524365** [lolisaikou/LazyStudy#118]
如题，小白了，请大家指导。当然先感恩大神的无私奉献。
看到有人的脚本时间是整分60秒，感觉不好，没有人可以把握的这准确。
请问大神，咱的脚本文章和视频的浏览时间是随机的还是固定的？
你的手机型号：华为P9

你的安卓版本：安卓8.0

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by lolisaikou** [comment]
大部分都是都是随机的
![image](https://user-images.githubusercontent.com/32028165/103216576-58725a80-4951-11eb-97bc-267dd1444272.png)
包括在脚本中大量使用的delay函数（随机范围在0~500ms）
![image](https://user-images.githubusercontent.com/32028165/103216675-8eafda00-4951-11eb-8402-77394b48a7dd.png)

**Comment by 85524365** [comment]
感谢大神能百忙中回复
