### ISSUE TITLE
2.6.3安装包好像有问题

### ISSUE THREAD

**Issue by zxcvbnm3111** [lolisaikou/LazyStudy#12]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by lolisaikou** [comment]
能不能提供详细信息啊
还有我这里基本都是安装测试好才发出去的

**Comment by lolisaikou** [comment]
以后会在[releases](https://github.com/lolisaikou/LazyStudy/releases)描述里增加[蓝奏云链接](https://lolisaikou.lanzous.com/b09l9qovg)

**Comment by jw8013** [comment]
@lolisaikou 
v2.6.3 解析软件包出现错误
v2.6.3_44P版本正常
2.6.3这个版本，下载下来图标都没有，没传完整吧

**Comment by lolisaikou** [comment]
> @lolisaikou
> v2.6.3 解析软件包出现错误
> v2.6.3_44P版本正常
> 2.6.3这个版本，下载下来图标都没有，没传完整吧

应该是Windows资源管理器自带的ftp背锅，前几个版本就有人反馈安装包错误，换了个filezilla
已经测试并重新上传了
