### ISSUE TITLE
请问是用哪个版本插件打包应用的，我打包的都不能正常运行

### ISSUE THREAD

**Issue by yk200842135** [lolisaikou/LazyStudy#120]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by zhuxuedefeng** [comment]
autojs免费版4.1.1 alpha2 打包插件对应4.1.1 Alpha2。注意:打包需要按项目进行打包，配置入口脚本。将题库文件，所有js脚本一起作为一个项目进行打包。
