### ISSUE TITLE
阅读文章的问题

### ISSUE THREAD

**Issue by Muyanglaw** [lolisaikou/LazyStudy#15]
44分这个，运行到阅读文章时，如果点到视频，程序自动返回重新收听广播，再次返回阅读文章时会不断的打开 电视台——联播频道的视频，重复大概6次左右，返回 学习——推荐页面，会往下拉一页，才会重新点开 推荐页面下的文章，但是如果在遇到视频，再返回阅读文章时又会出现不停地打开 电视台——联播频道的视频。

我用的小米8 ，不知道是不是个别问题

**Comment by lolisaikou** [comment]
能不能复现一些然后去输出界面截个图啊（打开懒人学习，按一下返回键把输出的日志放上来）
![image](https://user-images.githubusercontent.com/32028165/88482716-bb705780-cf95-11ea-8466-7fa6914b098c.png)
![image](https://user-images.githubusercontent.com/32028165/88482850-76005a00-cf96-11ea-87f1-f595c7808d67.png)
理论上不可能回过头再去看视频啊，看视频函数在上面。
而且整个脚本里看视频函数就出现了一次

**Comment by Muyanglaw** [comment]
不是重复运行 看视频 这个函数，是控制文章实际阅读的标号变量 t 判断有问题，推荐页面下滑动一般有2-6篇文章，实际点击一次t增加1，t超过当前页面下文章个数的时候就会自动打开 看视频 页面下的视频。我稍微改了下这部分就是先判断t < 4（6篇文章的比较少，一般推荐部分好多图片，有时候只有2篇文章），如果超过4就向下滑动一页，这样虽然也会出现上边问题，但是只要t超过4就会重新计算了。不知道是不是我的个例，不知道有没好的解决方法

**Comment by lolisaikou** [comment]
刚刚试了一下图片多的地方，~~在我手机上表现是会直接阅读页面上不存在的文章~~（看错了）
会出现点击不到文章就立刻触发翻页，并没有出现你描述的状况

**Comment by Muyanglaw** [comment]
那应该就是我手机的问题了，我换个手机试试，谢谢

**Comment by lolisaikou** [comment]
> 那应该就是我手机的问题了，我换个手机试试，谢谢

顺便我也是小米手机 米9 miui12

**Comment by aweder** [comment]
确实存在这个问题，我用的是华为的Nova4，因为在查文章时，文章列表会混有视频文章，一旦进入视频会导致收音广播会被打断，要解决这个问题，需要在阅读文章时先判断一下是否是视频，如果是视频就跳过

**Comment by zxcvbnm3111** [comment]
这个我知道，每个标题的右下角有播报的是文章

**Comment by zxcvbnm3111** [comment]
> 确实存在这个问题，我用的是华为的11月4日，因为在查文章时，文章列表会混有视频文章，一旦进入视频会导致收音广播会被打断，要解决这个问题，需要在阅读文章时先判断一下是否是视频，如果是视频就跳过

这个我知道，每个标题的右下角有播报的是文章

**Comment by elceric** [comment]
一加7T，44p存在类似问题。偶尔，在运行到阅读文章时，如果点到视频，程序自动返回重新收听广播，再返回文章则会播放新闻联播视频，进入回去收听广播的循环。如果不好解决，是否可以考虑在阅读文章时，不管是否点击到视频均不再返回点击广播，等看完文章后，再重新开启广播。
进入了视频界面，退出并进行下一篇文章！
因为广播被打断，重新收听广播...
正在收听广播...
进入了视频界面，退出并进行下一篇文章！
因为广播被打断，重新收听广播...
正在收听广播...
进入了视频界面，退出并进行下一篇文章！
因为广播被打断，重新收听广播...
正在收听广播...
……

**Comment by Muyanglaw** [comment]
不行的，即便是不返回点击广播，照样会点开联播视频，其实可以选择 订阅 里边的文章，我用了几天都没出现问题。推荐的容易出现这种情况

**Comment by elceric** [comment]
> 不行的，即便是不返回点击广播，照样会点开联播视频，其实可以选择 订阅 里边的文章，我用了几天都没出现问题。推荐的容易出现这种情况

已经更改为订阅。情况有一定好转，但党订阅的学习平台包含视频时，还是偶尔会出现这个问题。

**Comment by lolisaikou** [comment]
改成根据控件点击了，明天测试一下再发包
是我大意了，一直用的是autojs自己生成的签名，因为autojspro最新版有bug，需要卸载降级，所以原来的签名丢失，所以**本次更新需要卸载**（记得备份文章列表）这次我备份了签名文件，以后不会这样了
