### ISSUE TITLE
谢

### ISSUE THREAD

**Issue by inzaghigoal** [lolisaikou/LazyStudy#16]
特别感谢朋友的脚本，在每日繁忙工作中可以多休息一会，不用为这个操心，谢谢啦

**Comment by lolisaikou** [comment]
还要感谢

排名不分先后
>[**lgpersonal**](https://github.com/lgpersonal/)  
>[**kessil**](https://github.com/kessil/AutoXue)  
>[**ivanwhaf**](https://github.com/ivanwhaf/xxqg-helper)  
>[**studyhelperhelper**](https://github.com/studyhelperhelper/studyhelper)  
>[**wanghuisenior**](https://github.com/wanghuisenior)   
>[**colincai**](https://github.com/ivanwhaf/xxqg-helper/issues/75)    

有了他们这个脚本才能做的更好
