### ISSUE TITLE
希望阅读文章的判断方式更改一下

### ISSUE THREAD

**Issue by zxcvbnm3111** [lolisaikou/LazyStudy#18]
那些文章标题的右下角有播报就是文章，这样就不会进入视频文章页面导致听广播这种跳来跳去了

**Comment by lolisaikou** [comment]
不好实现啊，现在点击文章的依据是日期，并不是用控件方法点击的，没法做附加判断啊

**Comment by lnxcyq** [comment]
把list作一个限定就可以避免文章视频混淆。完美解决了这一问题

**Comment by zxcvbnm3111** [comment]
> 把list作一个限定就可以避免文章视频混淆。完美解决了这一问题

要怎么操作

**Comment by lnxcyq** [comment]
var readListView = className("android.support.v4.view.ViewPager").findOne().child(50).child(2);

**Comment by lolisaikou** [comment]
改成根据控件点击了，明天测试一下再发包
是我大意了，一直用的是autojs自己生成的签名，因为autojspro最新版有bug，需要卸载降级，所以原来的签名丢失，所以**本次更新需要卸载**（记得备份文章列表）
