### ISSUE TITLE
跟新网络题库

### ISSUE THREAD

**Issue by 740545082** [lolisaikou/LazyStudy#20]
我尝试更新网络题库，但是它一直显示正在更新网络题库？
是我的操作有问题吗？

**Comment by aweder** [comment]
实际上已经更新不用担心，我自己在这个的基础上使改了一版，使用的是网络题库，比这个要全些，http://49.235.90.76:5000/api/questions

**Comment by DoveBoy** [comment]
@lolisaikou 开发者大大，为什么题库一直更新不了？能解决一下吗？
![Screenshot_20200815-222316.jpg](https://user-images.githubusercontent.com/19201447/90314408-2209e500-df46-11ea-8b15-74b1467da154.jpg)

**Comment by lolisaikou** [comment]
> 我尝试更新网络题库，但是它一直显示正在更新网络题库？
> 是我的操作有问题吗？

能不能说一下安卓版本

**Comment by lolisaikou** [comment]
> @lolisaikou开发者大大，为什么题库一直更新不了？能解决一下吗？
> ![截图_20200815-222316.jpg](https://user-images.githubusercontent.com/19201447/90314408-2209e500-df46-11ea-8b15-74b1467da154.jpg)

这个是正常的，只是不会显示更新多少道题

**Comment by DoveBoy** [comment]
> > 我尝试更新网络题库，但是它一直显示正在更新网络题库？
> > 是我的操作有问题吗？
> 
> 能不能说一下安卓版本

安卓10

**Comment by lolisaikou** [comment]
> > > 我尝试更新网络题库，但是它一直显示正在更新网络题库？
> > > 是我的操作有问题吗？
> > 
> > 
> > 能不能说一下安卓版本
> 
> 安卓10

你点击更新题库后等30秒左右，然后按返回键，截图把日志发给我看看

**Comment by DoveBoy** [comment]
> > > > 我尝试更新网络题库，但是它一直显示正在更新网络题库？
> > > > 是我的操作有问题吗？
> > > 
> > > 
> > > 能不能说一下安卓版本
> > 
> > 安卓10
> 
> 你点击更新题库后等30秒左右，然后按返回键，截图把日志发给我看看

看了一下日志，虽然提示的是“更新undefined道题”，但是实际应该算是更新成功了，这个应该是显示上的bug吧
![Screenshot_20200816-145810.jpg](https://user-images.githubusercontent.com/19201447/90328717-2b8c5f00-dfd1-11ea-99a1-cec9fd652338.jpg)

**Comment by lolisaikou** [comment]
> > > > > 我尝试更新网络题库，但是它一直显示正在更新网络题库？
> > > > > 是我的操作有问题吗？
> > > > 
> > > > 
> > > > 能不能说一下安卓版本
> > > 
> > > 
> > > 安卓10
> > 
> > 
> > 你点击更新题库后等30秒左右，然后按返回键，截图把日志发给我看看
> 
> 看了一下日志，虽然提示的是“更新undefined道题”，但是实际应该算是更新成功了，这个应该是显示上的bug吧
> ![Screenshot_20200816-145810.jpg](https://user-images.githubusercontent.com/19201447/90328717-2b8c5f00-dfd1-11ea-99a1-cec9fd652338.jpg)

那这个问题的话，下个版本会修复

**Comment by lolisaikou** [comment]
已修复

**Comment by DoveBoy** [comment]
> 已修复

谢谢！
