### ISSUE TITLE
关于安装时出现签名问题的公告

### ISSUE THREAD

**Issue by lolisaikou** [lolisaikou/LazyStudy#21]
新版本还需要测试，预计明天（8月12日）上传
## 太长不看：因为本人原因，导致原签名丢失，所以**需要先卸载再安装新版本**（记得备份文章列表）
***
### 详细解释：  
因为autojs pro最新版本的bug，影响到打包应用，所以我需要卸载降级安装。加上之前我没有生成自己的签名文件，而是使用autojs安装时自带的随机生成的签名。所以降级安装时签名文件丢失，导致签名不一致，生成的安装包无法覆盖安装。  
因为我本人疏忽大意，给大家带来了麻烦，还请大家谅解。（最后提醒大家，重要文件记得备份）

**Comment by nick1374** [comment]
感谢作者

**Comment by zxcvbnm3111** [comment]
在哪下载

**Comment by wangwangyh** [comment]
谢谢作者

**Comment by jw8013** [comment]
@lolisaikou 
题库备份也留个吧，重装后，貌似之前手动录入的题目就没了
