### ISSUE TITLE
谢谢作者，新版有个问题。

### ISSUE THREAD

**Issue by wangwangyh** [lolisaikou/LazyStudy#22]
你的手机型号：
光速虚拟机
你的安卓版本：
7
错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：1，在收音之后就息屏了。2，剩余学习文章NaN篇，没法自动学了。前一版本无问题

**Comment by lolisaikou** [comment]
今日有大更新，需要等待适配

**Comment by lolisaikou** [comment]
已更新[这里下载](https://github.com/lolisaikou/LazyStudy/releases/)

**Comment by wangwangyh** [comment]
我靠。。你也太给力了吧
