### ISSUE TITLE
关于8月14日强国更新的公告

### ISSUE THREAD

**Issue by lolisaikou** [lolisaikou/LazyStudy#23]
正在适配，最快今天就可以

**Comment by lolisaikou** [comment]
# 2.6.4之前的版本（包括2.6.4）使用的签名和现在的签名不一样，所以升级需要卸载
-------
## 太长不看：因为本人原因，导致原签名丢失，所以**需要先卸载再安装新版本**（记得备份文章列表）
***
### 详细解释：  
因为autojs pro最新版本的bug，影响到打包应用，所以我需要卸载降级安装。加上之前我没有生成自己的签名文件，而是使用autojs安装时自带的随机生成的签名。所以降级安装时签名文件丢失，导致签名不一致，生成的安装包无法覆盖安装。  
因为我本人疏忽大意，给大家带来了麻烦，还请大家谅解。（最后提醒大家，重要文件记得备份）

**Comment by lolisaikou** [comment]
适配完成[release下载](https://github.com/lolisaikou/LazyStudy/releases/)

**Comment by wangwangyh** [comment]
为啥现在进去收听就停那儿了。。之前还会切出来，后台播放，这边继续操作。

**Comment by wangwangyh** [comment]
开始收听广播就停在那个界面了

**Comment by wangwangyh** [comment]
![20200815_104325](https://user-images.githubusercontent.com/48098120/90303835-31584680-dee4-11ea-9d1c-9ab9c3b471fc.jpg)
这个样子。。。

**Comment by xiaoxin-666** [comment]
我也是这样
