### ISSUE TITLE
新版学分判断可能出现的问题

### ISSUE THREAD

**Issue by yiaya001** [lolisaikou/LazyStudy#24]
aCount = Math.ceil((12 - myScores["我要选读文章"]) / 2); //文章个数

这行判断如果遇到以下情况：
当天已阅读文章1篇，单篇阅读6分钟。则剩余未读5篇。得分1+6=7分。
按照以上语句，则aCount=Math.ceil((12-7)/2)=3
语句判断为已阅读3篇（应为5篇），最终得分会少2分。

**Comment by lolisaikou** [comment]
emmm，没想到，但是因为两个被合并到一起了不好算啊

**Comment by arcqiufeng** [comment]
做的太精确没必要，人类学习的话也不会非常精确的。所以保险起见大不了多学几分钟，多学几篇文章应该也不要紧吧。

**Comment by lnxcyq** [comment]
其实可以这么处理，一是在读“分享”积分后，启动阅读程序（即判断“分享”没得分后，就开始去阅读文章6篇，每篇4秒左右），二是在读“我要选读文章”积分后，再启动新的阅读程序（读文章的数量 ＝12-6）

**Comment by lolisaikou** [comment]
为文章阅读增加了一个循环，直到循环次数大于3次或阅读文章满分停止，应该能修复这个问题了
