### ISSUE TITLE
都是要下载APK吗？

### ISSUE THREAD

**Issue by liangchaohua** [lolisaikou/LazyStudy#25]
请问有单JS版本吗？不用下载APK的

**Comment by lolisaikou** [comment]
下载这三个基本的文件就可运行了
[题库](https://github.com/lolisaikou/LazyStudy/blob/master/tiku.db)
[阅读模式控制](https://github.com/lolisaikou/LazyStudy/blob/master/article.txt)
[主程序](https://github.com/lolisaikou/LazyStudy/blob/onekey/xxqg_v3.1.3(fix).js)

**Comment by liangchaohua** [comment]
下载之后会报错。看了一下。预计要大修改 :）

**Comment by lolisaikou** [comment]
> 下载之后会报错。看了一下。预计要大修改 :）

不会啊，其他都是辅助功能
