### ISSUE TITLE
关于防风的一点感想

### ISSUE THREAD

**Issue by lovestudystrongcountry** [lolisaikou/LazyStudy#26]
感谢大佬继续维护这个项目
有一个疑问是autojs的基于控件点击，是什么原理？理想的状态应该是随机点击控件内一个坐标点，但是开坐标点后发现基于控件是没有坐标点点击的，这样算不算很明显的特征，如果被应用到监测方法中会导致封号呢？或者说如果不开无障碍，app就没有这个监测权限呢？小白不是很懂，有懂的大佬指点一下。
说一点关于防封的感想，用iv的脚本的时候习惯性的把延时全部设置随机变量。包括挑战答题轮数，连续答对次数。
还有就是脚本跟app独立，app单独放island隔离。

**Comment by lolisaikou** [comment]
42分的脚本在本项目[分支](https://github.com/lolisaikou/LazyStudy/tree/onekey)下开源

理论上只要下面三个文件就可以运行了
![image](https://user-images.githubusercontent.com/32028165/90269067-9a12d500-de8a-11ea-9807-1b7c5f85d169.png)

autojs的原理就是调用无障碍来获取控件和点击的，所以无法关闭
具体原理可以参考这篇安卓无障碍的文章<https://blog.csdn.net/weimingjue/article/details/82744146>

防封禁的话，我没有太注重过，只在这个脚本的挑战答题点击下一题的时间上和挑战答题次数上做了随机（而且随机范围很小）

**Comment by lovestudystrongcountry** [comment]
多谢大佬，发完issues之后我才发现有onekey分支，然后标题重新编辑了了一下，不知道为啥标题修改没有生效，如果可以的话希望加入随机数，delay函数改一下就行了。然后浏览文章滑动起始点也随机定义一下。
可能我没有表达清楚，我的意思是，如果强国没有无障碍权限的话，强国是否可以获取到我们点击坐标点的数据，如果获取不到的话，那我们也不必过于担心控件点击没有坐标数据而被封禁。相反如果强国后台可以获取坐标数据的话，那脚本就要大改，寻找控件区域，然后随机点击。

**Comment by 85524365** [comment]
见光死的案例实在是数不胜数，网友要想长久使用，必须闭源

**Comment by 85524365** [comment]
开源后，很快就会给封号，不能因个别人的一己私利，祸害天下网友，提凯源这个建议的其心可诛

**Comment by lolisaikou** [comment]
我查了一下资料，貌似没有对无障碍功能的检测方法
但是应用可以获取已安装应用列表和后台正在运行的应用，前者可以通过定制ui（如emui、miui、coloros）的权限管理或者在原生安卓上使用appops应用来禁用软件获取已安装应用列表，后者只能将app放在容器里例如你提到的island来防止他获取后台。
当然这上面提到的东西都只是假设，具体官方有没有实装这些反作弊功能，我们不得而知。
还有在这查找资料的过程中，找到了一种间接的反作弊的方法，通过手机传感器（如加速度传感器、重力传感器、方向传感器、陀螺仪、旋转矢量传感器）来获取点击前后传感器数据的变化来实现反作弊，不过安卓10已可以通过开发者选项禁用所有传感器。而且这个东西没有什么意义，如果用户是放在桌子上使用手机的，传感器的变化数值根本不大，阈值高了容易误判，阈值低了又没用了。
下个版本会尝试加入一些随机性

**Comment by lolisaikou** [comment]
还有你提到，强国能不能获取到点击位置，这个我可以告诉你，如果开发者想做检测的话很简单。
还有就是通过获取控件范围来实现随机位置点击，这个很难实现，因为autojs可以获取到需要翻页才能看到的控件，这样可能会误触或者根本无法点击。autojs的点击控件的具体实现方法我不太明白，所以上说法如有错误望大佬指出
