### ISSUE TITLE
42分浏览任务会一直卡在收听广播处

### ISSUE THREAD

**Issue by xiaoxin-666** [lolisaikou/LazyStudy#27]
当看完文章后就会卡住，控制台一直显示正在收听广播，让后就没有其他反应

**Comment by lolisaikou** [comment]
测试了一下我这里没有问题，应该属于偶现问题，应该和网速或者手机响应速度有关，只能尝试修复

**Comment by lolisaikou** [comment]
#28

**Comment by wangwangyh** [comment]
对啊。我还是有这个问题。。还是卡在正在收听广播那里。。之前都没问题。不知道是什么原因。2.6.6还是存在这个问题

**Comment by wangwangyh** [comment]
然后最近都是停在收听广播，接着息屏。就是要重新解锁亮屏，点下停止，回到主页，重新开始，才可以刷满。不能一键。

**Comment by lolisaikou** [comment]
已修复

**Comment by lovestudystrongcountry** [comment]
> 已修复

大佬，没有修复，还是卡在收听广播界面

**Comment by lovestudystrongcountry** [comment]
找到问题了，是autojs版本的问题，大佬用的是哪个版本，用你发布的包可以，自己autojs就一直不停的刷文章列表，要不就是卡在广播收听

**Comment by lolisaikou** [comment]
> 找到问题了，是autojs版本的问题，大佬用的是哪个版本，用你发布的包可以，自己autojs就一直不停的刷文章列表，要不就是卡在广播收听

我用的是pro8
