### ISSUE TITLE
[已解决]使用过程中会自动打开浏览器

### ISSUE THREAD

**Issue by szsyzx** [lolisaikou/LazyStudy#30]
你的手机型号：小米手机8屏幕指纹版

你的安卓版本：10

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by lolisaikou** [comment]
能不能截图让我看看日志

**Comment by lolisaikou** [comment]
具体是运行到哪里出现的

**Comment by szsyzx** [comment]
在点击本地频道后自动打开浏览器

**Comment by szsyzx** [comment]
![2020-08-16 20 47 03](https://user-images.githubusercontent.com/21995452/90334633-ac634f00-e001-11ea-94e3-080027566d3e.jpg)

**Comment by szsyzx** [comment]
https://ftp.bmp.ovh/imgs/2020/08/726a5ece6ad59a98.jpg

**Comment by lolisaikou** [comment]
用的是虚拟按键还是小白条

**Comment by szsyzx** [comment]
你说的是导航模式吗，虚拟按键不是全屏手势

**Comment by lolisaikou** [comment]
到权限管理里禁止强国定位，然后到新思想右边的地方频道（因为你授权了定位，所以这里会是你的省份），切换地区到北京
![image](https://user-images.githubusercontent.com/32028165/90334998-38767600-e004-11ea-8416-d808ea7c50ba.png)
然后明天再观察一下

**Comment by szsyzx** [comment]
按照老大的方法解决了谢谢
