### ISSUE TITLE
2.6.7 版本运行报错

### ISSUE THREAD

**Issue by DoveBoy** [lolisaikou/LazyStudy#31]
你的手机型号：一加5T

你的安卓版本：10

错误的截图：![Screenshot_20200817-083605.jpg](https://user-images.githubusercontent.com/19201447/90347795-047f6d00-e065-11ea-8a4b-091f90f232db.jpg)
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：启动脚本，开始学习，自动打开强国软件后就报错

**Comment by lolisaikou** [comment]
忘记加random函数了，已经修复了

**Comment by DoveBoy** [comment]
> 忘记加random函数了，已经修复了

收到，测试已能正常使用了

**Comment by Ivan-cn** [comment]
> 忘记加random函数了，已经修复了

有一台7.1的手机更新题库失败，但在另一台9.0和10.0的又正常。
另随机背景能否有勾选框？我有一台是墨水屏手机看，背景化得很，还不如没有背景的使用起来好看一点。

**Comment by DoveBoy** [comment]
> 忘记加random函数了，已经修复了
又出现新的错误了

![Screenshot_20200818-070629.jpg](https://user-images.githubusercontent.com/19201447/90452713-66051180-e121-11ea-95f8-db006b2aaec4.jpg)

**Comment by KB64ba** [comment]
var htmlString = Jsoup.connect("http://49.235.90.76:5000").maxBodySize(0).timeout(1000000).get();

imeout(1000000)把里面的数字改大点就，

**Comment by Leo4ML** [comment]
> > 忘记加random函数了，已经修复了
> > 又出现新的错误了
> 
> ![Screenshot_20200818-070629.jpg](https://user-images.githubusercontent.com/19201447/90452713-66051180-e121-11ea-95f8-db006b2aaec4.jpg)

同样报错，https://ftp.bmp.ovh/imgs/2020/08/095c4b4b4a0c59a8.png

**Comment by lolisaikou** [comment]
@Leo4ML @DoveBoy  我的锅，已经修复了
