### ISSUE TITLE
辛苦辛苦，希望把开始浏览的业务逻辑改为全部一次44分，保留特殊答题（专项，每周）按钮

### ISSUE THREAD

**Issue by wanghuisenior** [lolisaikou/LazyStudy#32]
我主页自己改的那个不想更新了，旧版本可以一次不用管直接44分的，希望添加这个功能，另外想咨询下关于签名是啥，不懂有什么用

**Comment by lolisaikou** [comment]
现在满分是42分啊，你只需要下载42p的版本就行了。
签名就是为了识别程序的身份，防止被其他人恶意篡改，是安卓打包apk必须的东西。

**Comment by wanghuisenior** [comment]
好的
