### ISSUE TITLE
可否一键42分版中也分别提供各部分单独学习按钮

### ISSUE THREAD

**Issue by arcqiufeng** [lolisaikou/LazyStudy#34]
没有必要分成两个版本啊。现在两个都装也挺麻烦的。

**Comment by zxcvbnm3111** [comment]
>  #没有必要分成两个版本啊.现在两个都装也挺麻烦的.


不是看你自己喜欢那个装那个，一个就行了

**Comment by arcqiufeng** [comment]
> > #没有必要分成两个版本啊.现在两个都装也挺麻烦的.
> 
> 不是看你自己喜欢那个装那个，一个就行了

那能不能在一键版里也提供单独学习文章、单独分享、单独订阅的按钮。

昨天我一键弄完发现没有做满42分。文章没有满（前面也曾发现过订阅不满，或者分享不满）。然后又不想全部再来一遍，所以又去下了一个单独分功能的版本。如果能提供单独功能按钮，那就可以事后看一下缺啥补啥。

是不是我使用方法不对？

**Comment by zxcvbnm3111** [comment]
> > > #没有必要分成两个版本啊.现在两个都装也挺麻烦的.
> > 
> > 
> > 不是看你自己喜欢那个装那个，一个就行了
> 
> 那能不能在一键版里也提供单独学习文章、单独分享、单独订阅的按钮.
> 
> 昨天我一键弄完发现没有做满42分.文章没有满(前面也曾发现过订阅不满，或者分享不满)。然后又不想全部再来一遍，所以又去下了一个单独分功能的版本.如果能提供单独功能按钮，那就可以事后看一下缺啥补啥.
> 
> 是不是我使用方法不对？

正常的，这只是辅助而已，

**Comment by lolisaikou** [comment]
我给文章阅读加了个循环，直到循环次数大于3次或阅读文章满分停止，应该能修复文章分数不够的问题
