### ISSUE TITLE
从ivanwhaf的评论找过来的，总算找到一个在更新的作者了。

### ISSUE THREAD

**Issue by Lee-20** [lolisaikou/LazyStudy#37]
我自己在用的脚本也是综合了看到的各种功能，答题部分已经和ivanwhaf的原版很不一样了，准备下载lolisaikou的学习一下

**Comment by lolisaikou** [comment]
刚刚给ivanwhaf提交了PR，没有加花里胡哨的功能，不知道他会不会接受

**Comment by Lee-20** [comment]
> 刚刚给ivanwhaf提交了PR，没有加花里胡哨的功能，不知道他会不会接受

可能没时间打开？

我自己的改了这些功能，到处看的

    修复文章视频判定，视频的展开desc更新为text
    修复在文章学习过程中遇到视频时，不继续听广播的bug
    修复填空题“徐特立”bug —— 来自评论区 @lolisaikou
    修复积分获取bug
    新增连续视频判定，简单解决学习文章进入视频的问题
    新增记录文章、视频标题，防止重复学习（分开记录）—— 来自“auto_xxqg_android5.js”（没找到作者）
    新增订阅函数 —— 来自评论区 @colincai
    大幅度改动答题函数，新增题库的成长性 —— 来自@MisterZakary 的开源项目“-LazyStudy”
    新增获取姓名函数，新增发送企业微信意图
