### ISSUE TITLE
挑战答题不会6分停止的吗

### ISSUE THREAD

**Issue by enterlet** [lolisaikou/LazyStudy#38]
我看README.md
> 挑战答题：进入挑战答题界面，点击“挑战答题”，开始答题，答错会自动重新开始，得到6分停止。

但是每次过了6分还是会继续答。。。

**Comment by lolisaikou** [comment]
因为每日答题数是随机的，尽量模仿人的操作，随机范围在5~7之间

**Comment by enterlet** [comment]
> 因为每日答题数是随机的，尽量模仿人的操作，随机范围在5~7之间

@lolisaikou 今天我试着没有手动停止，都答到22题了，答错了才停。应该超了随机范围了吧

**Comment by lolisaikou** [comment]
是bug我重新打包了
