### ISSUE TITLE
视频有时候刷不满

### ISSUE THREAD

**Issue by lovestudystrongcountry** [lolisaikou/LazyStudy#39]
建议视频分数也加一个判断循环，如果没有刷满，刷一下百灵也是不错的选择，目前联播频道的视频不够刷。
由于pro8跟免费版不兼容，导致脚本在免费版上不能正常运行，请求大佬加入更多自定义参数。
比如delay函数的random范围。
评论内容
挑战答题轮次，连续答对次数
文章阅读时长
视频浏览时长
刷联播频道还是百灵

**Comment by lolisaikou** [comment]
我fork了ivanwhaf的脚本，并且修复了错误，[看看](https://github.com/lolisaikou/xxqg-helper)
