### ISSUE TITLE
求问

### ISSUE THREAD

**Issue by liangchaohua** [lolisaikou/LazyStudy#4]
你的手机型号：小米MIX

你的安卓版本：安卓9 miui11

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/，然后把图片链接贴在这里）

错误描述：执行浏览的时候自动跳到聊天界面。 
auto.js 4.0.1beta  qg版本2.14.0

**Comment by lnxcyq** [comment]
正常，那是因为这个阅读文章的代码的list没有限定好

**Comment by lolisaikou** [comment]
找不到解决办法TAT~~我在好几个手机上测试都没问题
~~蹲一个dalao~~
