### ISSUE TITLE
7.1的旧机更新题库提示语句失败

### ISSUE THREAD

**Issue by Ivan-cn** [lolisaikou/LazyStudy#40]
你的手机型号：红米4x

你的安卓版本：7.1

错误描述：7.1的旧机更新题库提示语句失败，但安卓9、10的手机却正常更新，log提示好像是说java语句使用错误之类。

Log:
18:51:15.145/E: Thread[main,5]:     函数importClass必须与一个类一起调用;改为使用"[JavaPackage org.jsoup.Jsoup]". (<init>#14)
    函数importClass必须与一个类一起调用;改为使用"[JavaPackage org.jsoup.Jsoup]".
    at <init>:14:0
    at file:/data/data/com.lazyxue.onekey/files/project/updateTikuNet.js:4:0
    at _load (file:///android_asset/modules/jvm-npm.js:60:0)
    at UI.js.js:308:0

**Comment by lolisaikou** [comment]
我测试了一下，确实会报错。
查了资料也问了大佬，不知道怎么解决。
有人说是autojs版本的问题，我试着用autojs4.1.1来运行（我打包和测试用的是pro8）更新题库的代码。第一次报错了，但是返回重新运行就不会报错了，不过更新的进度条一直显示，更新成功的提示也一直没有。我也不知道如何解决了，不过最近几个版本我都更新了内置的题库。
我试着重构一下更新题库的代码吧，不用jsoup来解析，试着从这里获取<http://49.235.90.76:5000/api/questions>而不是<http://49.235.90.76:5000>。不过最近就要开学，下个版本可能不知道要到什么时候了。

**Comment by Ivan-cn** [comment]
> 我测试了一下，确实会报错。
> 查了资料也问了大佬，不知道怎么解决。
> 有人说是autojs版本的问题，我试着用autojs4.1.1来运行（我打包和测试用的是pro8）更新题库的代码。第一次报错了，但是返回重新运行就不会报错了，不过更新的进度条一直显示，更新成功的提示也一直没有。我也不知道如何解决了，不过最近几个版本我都更新了内置的题库。
> 我试着重构一下更新题库的代码吧，不用jsoup来解析，试着从这里获取http://49.235.90.76:5000/api/questions而不是http://49.235.90.76:5000。不过最近就要开学，下个版本可能不知道要到什么时候了。

确实不急，我也是偶尔发现7.1的报错而已，但9.0和10.0的正常使用，慢慢来，学业为重。

**Comment by lolisaikou** [comment]
已更新

**Comment by KB64ba** [comment]
log("开始更新数据库...");
    var htmlString = Jsoup.connect("http://49.235.90.76:5000").maxBodySize(0).timeout(1000000).get();

把timeout后面括号的数值改大就可以了， 这个好像是响应还是字符接收的限值，大概是这个意思，我改大之后就没出现过更新报错，除了是缓存错误才有
