### ISSUE TITLE
请问阅读模式选择是干什么用的？

### ISSUE THREAD

**Issue by arcqiufeng** [lolisaikou/LazyStudy#41]
如题

**Comment by KB64ba** [comment]
选看推荐、还是订阅里面的文章

**Comment by arcqiufeng** [comment]
> 选看推荐、还是订阅里面的文章

是指自动文章阅读时，阅读哪个版块吗？自己手工订阅，然后派这位去自动阅读？

**Comment by lolisaikou** [comment]
这个选项是控制程序去阅读你选择的文章列表。如果你选择`“推荐”`，程序就会阅读`“推荐”`列表下的文章；如果你选择`“订阅”`，程序就会阅读`“订阅”`列表下的文章。
