### ISSUE TITLE
感谢大神：42分apk版2.6.8每次最后学习视频不满，每次少学1个，然后卡住，其他正常，

### ISSUE THREAD

**Issue by 85524365** [lolisaikou/LazyStudy#42]
你的手机型号：华为p9

你的安卓版本：8.0

错误的截图：
https://ftp.bmp.ovh/imgs/2020/08/9936ffcb7594f96f.jpg
错误描述：
42分apk版2.6.8每次学习视频不满，每次少学1个，然后卡住不动，出现红字闪动，提示离开第6个视频了。
而实际上包含新闻联播在内，每一次都是第4个视频不能学习。
这个时候，如果手动点一下第4个视频，就又重新计时了，而且学习时间到期后，还能返回主界面的。
感谢大神，希望软件越来越完美

**Comment by 85524365** [comment]
[img]https://ftp.bmp.ovh/imgs/2020/08/b6ebc15978f12ef1.jpg[/img]
[img]https://ftp.bmp.ovh/imgs/2020/08/dc86a77c5108ebf6.jpg[/img]

**Comment by 85524365** [comment]
大神，今天又出现错误了，这次是从第5个就开始报错，然后卡住了，比昨天又增加一个

**Comment by zxcvbnm3111** [comment]
> 大神，今天又出现错误了，这次是从第5个就开始报错，然后卡住了，比昨天又增加一个

不是都第6个出错吗

**Comment by 85524365** [comment]
是这样的：
昨天之前，是从第6个开始报错，余下1个未学。
今天开始，是从第5个开始报错，余下2个未学。

**Comment by lolisaikou** [comment]
下个版本修复

**Comment by lolisaikou** [comment]
已修复
