### ISSUE TITLE
视频在移动信号下无法获取积分

### ISSUE THREAD

**Issue by elceric** [lolisaikou/LazyStudy#45]
视频在移动信号下，显示“当前为非WIFI网络，即将消耗XX流量”，导致无法获取积分
可否增加判断，当出现此情况时，点击继续播放呢？
另外，视频采用百灵来看是否效率会更高？

**Comment by zxcvbnm3111** [comment]
> 视频在移动信号下，显示“当前为非WiFi网络，即将消耗XX流量”，导致无法获取积分
> 可否增加判断，当出现此情况时，点击继续播放呢？
> 另外，视频采用百灵来看是否效率会更高？

浪费时间，设置里面设置一下就可以自动在移动信号下播放
