### ISSUE TITLE
提个建议，软件名称问题

### ISSUE THREAD

**Issue by 1celife** [lolisaikou/LazyStudy#46]
一键42分和普通版软件名称一样，两个都在用，可否把两个软件名字改成不一样的，比如改成 懒人学习42  之类的，好做区分。

**Comment by Dr8pus** [comment]
> 一键42分和普通版软件名称一样，两个都在用，可否把两个软件名字改成不一样的，比如改成 懒人学习42  之类的，好做区分。
> 

可用mt管理器改
