### ISSUE TITLE
为什么不把一键42分和原版整合到一起？

### ISSUE THREAD

**Issue by jianyu0323** [lolisaikou/LazyStudy#47]
感谢作者的更新。之前用的就是ivanwhaf的xxqg-helper，后面看到了原作者的LazyStudy,感觉在题库更新上比强国助手要强，但是觉得不能一键所以当时毫无基础的我把两者费劲整合在一起改了改，但后面一更新要再重弄就放弃了。今天偶然发现大神接手了懒人并进行了更新，并贴心提供了一键42分版，下载一键42分版发现不能自动打开强国APP···
同时我想问，为什么不把两者整合在一起？在悬浮窗里“开始浏览”上面，更好的是在功能主页面的打开悬浮窗上面添加一个“一键学习”功能？一个软件同时实现两者不是更好么？代码本身很小也不会增加多大的空间，不知道有没有难度。
我是绝对的小白，没有不尊重作者劳动成果的意思。再次感谢作者的无私更新！
修改：今天又试了下，一键版可以自动启动强国APP。昨天不行可能是在辅助功能里选择“开始预览”的。我只是在不清楚整合是否有工作量的情况下提供的建议，如果不合适的请作者忽略，我只是觉得整合一起可能会有利于后期维护更新才提的建议，否则每次还要打包两款APP。
对了，作者有一键版的脚本吗？还是喜欢直接用JS版的，直接更新APP的话原来的题库也会被替换吧

**Comment by zxcvbnm3111** [comment]
> 感谢作者的更新。之前用的就是ivanwhaf的xxqg-helper，后面看到了原作者的LazyStudy,感觉在题库更新上比强国助手要强，但是觉得不能一键所以当时毫无基础的我把两者费劲整合在一起改了改，但后面一更新要再重弄就放弃了。今天偶然发现大神接手了懒人并进行了更新，并贴心提供了一键42分版，下载一键42分版发现不能自动打开强国APP···
> 同时我想问，为什么不把两者整合在一起？在悬浮窗里“开始浏览”上面，更好的是在功能主页面的打开悬浮窗上面添加一个“一键学习”功能？一个软件同时实现两者不是更好么？代码本身很小也不会增加多大的空间，不知道有没有难度。
> 我是绝对的小白，没有不尊重作者劳动成果的意思。再次感谢作者的无私更新！

能不能提些好的建议，是不是比懒人还懒啊

**Comment by zxcvbnm3111** [comment]
一键42分不就是一键学习吗

**Comment by jianyu0323** [comment]
> > 感谢作者的更新。之前用的就是ivanwhaf的xxqg-helper，后面看到了原作者的LazyStudy,感觉在题库更新上比强国助手要强，但是觉得不能一键所以当时毫无基础的我把两者费劲整合在一起改了改，但后面一更新要再重弄就放弃了。今天偶然发现大神接手了懒人并进行了更新，并贴心提供了一键42分版，下载一键42分版发现不能自动打开强国APP···
> > 同时我想问，为什么不把两者整合在一起？在悬浮窗里“开始浏览”上面，更好的是在功能主页面的打开悬浮窗上面添加一个“一键学习”功能？一个软件同时实现两者不是更好么？代码本身很小也不会增加多大的空间，不知道有没有难度。
> > 我是绝对的小白，没有不尊重作者劳动成果的意思。再次感谢作者的无私更新！
> 
> 能不能提些好的建议，是不是比懒人还懒啊

建议不好吗？能一个软件加个选项实现现在两个软件的功能，现在作者还要上传维护两个不更麻烦？评论区里不也有两个软件都安装都需要用的，还要装两个。

**Comment by jianyu0323** [comment]
> 一键42分不就是一键学习吗

**我是喜欢用一键版的，但考虑到现作者及原作者一直更新分步的，加上确实有人提到过两款APP都要用才提出了这个看法。。可能不合适，已经被上边的喷过了。纯纯的小白，我是真不懂，我都是乱说的

**Comment by zxcvbnm3111** [comment]
> **我是喜欢用一键版的，但考虑到现作者及原作者一直更新分步的，加上确实有人提到过两款APP都要用才提出了这个看法。。可能不合适，已经被上边的喷过了。纯纯的小白，我是真不懂，我都是乱说的】



还小白，你是就找不到这个了

**Comment by jianyu0323** [comment]
> > **我是喜欢用一键版的，但考虑到现作者及原作者一直更新分步的，加上确实有人提到过两款APP都要用才提出了这个看法。。可能不合适，已经被上边的喷过了。纯纯的小白，我是真不懂，我都是乱说的】
> 
> 还小白，你是就找不到这个了

确实小白啊，没学过这些语言。至于怎么找到这个的，去年灵机一动百度了下，发现了其他网站助手的介绍，当时说明的还是最简单的第一版，单纯的坐标+时间浏览的代码，跳转到这里才发现了助手已经更新成了神器。然后从助手的作者那看到了懒人的原作者lgpersonal，喜欢助手的一键+懒人的题库更新，就想通过最笨的方法复制黏贴到一块，经常提示出错弄了很长时间很多版JS，但一更新就要重新弄就放弃了。而且助手那个通过提示找到的答案如果是错的也不会自动纠正，总有遗憾。昨天才看到lolisaikou大神接更了懒人，看到还要分两款APP就想着按我之前的设想提下意见····

**Comment by zxcvbnm3111** [comment]
> > > **我是喜欢用一键版的，但考虑到现作者及原作者一直更新分步的，加上确实有人提到过两款APP都要用才提出了这个看法。。可能不合适，已经被上边的喷过了。纯纯的小白，我是真不懂，我都是乱说的】
> > 
> > 
> > 还小白，你是就找不到这个了
> 
> 确实小白啊，没学过这些语言。至于怎么找到这个的，去年灵机一动百度了下，发现了其他网站助手的介绍，当时说明的还是最简单的第一版，单纯的坐标+时间浏览的代码，跳转到这里才发现了助手已经更新成了神器。然后从助手的作者那看到了懒人的原作者lgpersonal，喜欢助手的一键+懒人的题库更新，就想通过最笨的方法复制黏贴到一块，经常提示出错弄了很长时间很多版JS，但一更新就要重新弄就放弃了。而且助手那个通过提示找到的答案如果是错的也不会自动纠正，总有遗憾。昨天才看到lolisaikou大神接更了懒人，看到还要分两款APP就想着按我之前的设想提下意见····

行行行
