### ISSUE TITLE
挑战答题里有一类题目无法答对

### ISSUE THREAD

**Issue by forbbs** [lolisaikou/LazyStudy#48]
现在题库里有一种题目：题干叫“选择词语的正确词形”。
所有题目都是这个题干，但每道题答案不一样。

目前好像无法答对这种题型，只能靠蒙。

--------------------------------------------------------------

【A 】 选择词语的正确词形____。
 ◦一副对联
◦一幅对联

【B 】 选择词语的正确词形____。
 ◦粘合剂
◦黏合剂

**Comment by admin0008** [comment]
现在的tiku数据库只有question，没有option，所以搜索不到唯一值

想要答对这类题目，唯一办法就是把题库都更新成 题目，选项，答案，安然搜题找答案时按照“题目和选项”来搜题，确保唯一。

**Comment by forbbs** [comment]
其实原版这里http://49.235.90.76:5000是答案、题干都全的。
主要是tiku.db里只做了选项和题干。

可以考虑另起炉灶，弄一个tiku2.db，把整个题目选项答案都放进去。

**Comment by admin0008** [comment]
1.修改网络题库更新，更新timu包括题干和选项；
2.修改getScores函数，通过“学分明细”获取明确学分；
3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
4.其它小修改若干……

**Comment by lnxcyq** [comment]
> 1.修改网络题库更新，更新timu包括题干和选项；
> 2.修改getScores函数，通过“学分明细”获取明确学分；
> 3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
> 4.其它小修改若干……
大佬，你好。用了你的代码，挑战答题很好了，但是每日答题里也有那个种题目相同的，能不能把每日答题的代码也修改一下。谢谢。

**Comment by lolisaikou** [comment]
在做了在做了
