### ISSUE TITLE
关于挑战答题5题限制

### ISSUE THREAD

**Issue by nickyleu** [lolisaikou/LazyStudy#49]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：
能不能取消5题限制，因为点点通是15题满分，或者我想挑战答题只有提示功能，可以锻炼学习通关，不知道能否实现

**Comment by nickyleu** [comment]
还有个问题就是挑战题库如何更新，支持自己导入更新不

**Comment by admin0008** [comment]
把每轮答题数调到2000就行了，现在挑战答题到1200多道就提示通关，不能再继续了

**Comment by nickyleu** [comment]
app怎么修改呀？
现在导入的题库只有7852题，能自己制定更不，如何修改？

**Comment by admin0008** [comment]
请看我fork的版本：
1.修改网络题库更新，更新timu包括题干和选项；
2.修改getScores函数，通过“学分明细”获取明确学分；
3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
4.其它小修改若干……

**Comment by nickyleu** [comment]
谢谢大佬的解答，不过我是个小白，不太会操作

**Comment by admin0008** [comment]
我也是github新人，帐号才注册几天。
我只是修改了几个源码js文件，你可以自行下载，替换就可以了。
如果这个也不会，只能叫作者修改后，然后打包，发布，让你们直接下载打包好的apk。

**Comment by nickyleu** [comment]
zip文件，我怎么把它打包成apk，里面文件我修改了下，直接改文件后缀不行

**Comment by admin0008** [comment]
不需要打包，你安装个 autojs，然后把文件放到里面，运行。具体请百度，或者看作者的md

**Comment by nickyleu** [comment]
autojs你用哪个版本的编辑？

**Comment by admin0008** [comment]
> autojs你用哪个版本的编辑？

auto.js版本4.1.1，听说是最后一个免费版

**Comment by nickyleu** [comment]
最后怎么样打包成你这样的apk，我修改了下challengeanswers.js里面的个别条件，因为光这个文件，调用不了题库，我用的VScode

**Comment by admin0008** [comment]
我基本都是手机编辑而已（效率感人😂）
个人觉得没必要打包，autojs里运行更稳定，而且修改方便。另外，打包成apk是需要另外安装打包插件，请baidu。

**Comment by haoguowei98** [comment]
你这个修改的有Bug，本地频道不能自动运行，阅读文章时不能进入文章里，一直处于外围翻页状态…

**Comment by haoguowei98** [comment]
> 请看我fork的版本：
> 1.修改网络题库更新，更新timu包括题干和选项；
> 2.修改getScores函数，通过“学分明细”获取明确学分；
> 3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
> 4.其它小修改若干……

你这个修改的有Bug，本地频道不能自动运行，阅读文章时不能进入文章里，一直处于外围翻页状态…

**Comment by hanguowei98** [comment]
> 请看我fork的版本：
> 1.修改网络题库更新，更新timu包括题干和选项；
> 2.修改getScores函数，通过“学分明细”获取明确学分；
> 3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
> 4.其它小修改若干……

@admin0008   你这个修改的有Bug，本地频道不能自动运行，阅读文章时不能进入文章里，一直处于外围翻页状态…

**Comment by admin0008** [comment]
> > 请看我fork的版本：
> > 1.修改网络题库更新，更新timu包括题干和选项；
> > 2.修改getScores函数，通过“学分明细”获取明确学分；
> > 3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
> > 4.其它小修改若干……
> 
> @admin0008 你这个修改的有Bug，本地频道不能自动运行，阅读文章时不能进入文章里，一直处于外围翻页状态…

我只在本人测试过，你说的情况我也不太清楚。
至于本地频道，我是把xxqg的定位权限关掉的，另外我用的2.15.1的xxqg版本，所以请保持xxqg版本一致和关闭他的定位权限再测试，麻烦了

**Comment by KB64ba** [comment]
> > > 请看我fork的版本：
> > > 1.修改网络题库更新，更新timu包括题干和选项；
> > > 2.修改getScores函数，通过“学分明细”获取明确学分；
> > > 3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
> > > 4.其它小修改若干……
> > 
> > 
> > @admin0008 你这个修改的有Bug，本地频道不能自动运行，阅读文章时不能进入文章里，一直处于外围翻页状态…
> 
> 我只在本人测试过，你说的情况我也不太清楚。
> 至于本地频道，我是把xxqg的定位权限关掉的，另外我用的2.15.1的xxqg版本，所以请保持xxqg版本一致和关闭他的定位权限再测试，麻烦了

在检查出已收藏时自动翻页，应该加多个判断一直检查到收藏再翻页，避免翻页超出文章或者无日期文章。

新闻联播的文章不多，如果已检查到收藏就翻页很快就到底了，又一直翻页，没有判断无视频直接结束。同时在视频页有时会卡住不翻页。文章有时又一直翻页，可能是检测播报有问题，应该加个缓冲时间

**Comment by admin0008** [comment]
因为新闻联播都是每天晚上更新的，就算数量是有限的，但也超6个了，所以一般情况不会出现学不够的情况。

但是如果没真正看，或者昨晚刚更新就学习，早上又继续学，的确视频数不够12个的话，会出现你说的情况。
所以下次更新会加个到底的退出判断。

**Comment by admin0008** [comment]
> > > > 请看我fork的版本：
> > > > 1.修改网络题库更新，更新timu包括题干和选项；
> > > > 2.修改getScores函数，通过“学分明细”获取明确学分；
> > > > 3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
> > > > 4.其它小修改若干……
> > > 
> > > 
> > > @admin0008 你这个修改的有Bug，本地频道不能自动运行，阅读文章时不能进入文章里，一直处于外围翻页状态…
> > 
> > 
> > 我只在本人测试过，你说的情况我也不太清楚。
> > 至于本地频道，我是把xxqg的定位权限关掉的，另外我用的2.15.1的xxqg版本，所以请保持xxqg版本一致和关闭他的定位权限再测试，麻烦了
> 
> 在检查出已收藏时自动翻页，应该加多个判断一直检查到收藏再翻页，避免翻页超出文章或者无日期文章。
> 
> 新闻联播的文章不多，如果已检查到收藏就翻页很快就到底了，又一直翻页，没有判断无视频直接结束。同时在视频页有时会卡住不翻页。文章有时又一直翻页，可能是检测播报有问题，应该加个缓冲时间

已更新视频学习翻页bug！
文章学习我这边是正常的，不会乱翻页啊，如果有乱翻页的，麻烦检查测试环境是否一致，我的是：android9.0/autojs4.1/xxqg2.15.1/flyme8.1UI。（如xxqg版本、手机系统版本等）

**Comment by 1130078044** [comment]
> 请看我fork的版本：
> 1.修改网络题库更新，更新timu包括题干和选项；
> 2.修改getScores函数，通过“学分明细”获取明确学分；
> 3.修改挑战答题中，获取题库答案，使之通过“题干+选项”进行照题，确保能找到正确答案（使用前请更新题库，确保题库的question带选项字符串）；
> 4.其它小修改若干……

有个设想，不知道能不能实现。
挑战答题比如选了A，如果答错了，就把题目加入题库，题库答案1为B，题库答案2为C，题库答案3为D。
下次再遇到这个题，直接按题库答案1点击（也就是B），如果对了，那就不用管了。如果错了，那就把题库答案1换成C，题库答案2换成D。
等于不管有几个选项，都按题库答案1点击。
这样的话，每道题最多答3次，最后题库里就出来绝对正确的答案了。
这样就能自己添加题库答案了。

**Comment by admin0008** [comment]
不用这么麻烦，直接把正确答案更新到题库就行了，其实这个就是自动题库功能，其实早已实现了，不过懒得刷题而已，网上题库更新更快，所以一直私用😂，没放出来。

**Comment by nickyleu** [comment]
私用的这个版本能分享下不，现在这个题库缺太多了，我想更新都无从下手
还有强国更新了，挑战答题进去卡住不动




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lolisaikou/LazyStudy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 晚上7:06
收件人:&nbsp;"lolisaikou/LazyStudy"<LazyStudy@noreply.github.com&gt;;
抄送:&nbsp;"寳寳dē伙计"<23628559@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lolisaikou/LazyStudy] 关于挑战答题5题限制 (#49)





 
不用这么麻烦，直接把正确答案更新到题库就行了，其实这个就是自动题库功能，其实早已实现了，不过懒得刷题而已，网上题库更新更快，所以一直私用😂，没放出来。

**Comment by nickyleu** [comment]
私用的能分享下么，现在的题库缺太多，我想更新都无从下手，可以的话加我QQ或微信23628559

**Comment by admin0008** [comment]
`

> 私用的能分享下么，现在的题库缺太多，我想更新都无从下手，可以的话加我QQ或微信23628559

现在xxqg任务的确简单了，包括时长、挑战答题数以及答题时间（微信各种搜题的小程序，搜题也够时间）。
如果是完成学分任务，感觉没必要，纵使有错，脚本自动刷到5题也不用费多久时间。
放出来，必然更多人用脚本刷题，来让本地题库更新（正常人不会刷题的，除了部分要参加比赛的），这样官方很可能就会加强针对脚本这一块的检测力度，到时都凉凉了，其实现在都凉了一大半了，这也是为什么简单的bug，也没人更新的原因。 

PS：个人更新的话，可以用ui的题库功能，手动修改或新增来更新。

**Comment by nickyleu** [comment]
UI题库昨天就更新不成了，这个题库更新是在我手机端还是网络，什么格式可以批量导入？

**Comment by nickyleu** [comment]
我其实弄挑战答题这个，就是为了比赛和练习使用，一个是想使用自己的题库，另一个就是有提示就行，不用自动点击，太小白了，所以不太会修改challengeAnswer.js那个文件的内容，所以想加下你请教下

**Comment by admin0008** [comment]
由于网络题库不能更新，上传了个人的 tiku.db，有需要的到我的fork的版本中下载。

**Comment by nickyleu** [comment]
大佬问下，questions.json也是题库文件吗，这个怎么使用
