### ISSUE TITLE
2.6.2在安装时解析包错误

### ISSUE THREAD

**Issue by xiaotong1995** [lolisaikou/LazyStudy#5]
你的手机型号：redmi k20 Pro

你的安卓版本：10

错误的截图：https://cdn.jsdelivr.net/gh/xiaotong1995/PIC/2020/07/09/2daa65.png

（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：下载安装时解析包出现问题，在2.6.1未出现

**Comment by lolisaikou** [comment]
我重新上传了，点[这里](https://github.com/lolisaikou/LazyStudy/releases/download/v2.6.2/lazyxue_v2.6.2.apk)下载

**Comment by xiaotong1995** [comment]
Ok，问题解决了~
