### ISSUE TITLE
学习强国我要答题布局改变，导致软件卡在这里

### ISSUE THREAD

**Issue by szsyzx** [lolisaikou/LazyStudy#52]
你的手机型号：小米9

你的安卓版本：10

错误的截图：https://ftp.bmp.ovh/imgs/2020/09/d58223d37d7cc13f.jpg

错误描述：学习强国我要答题布局改变，导致软件卡在这里

**Comment by 85524365** [comment]
都出现啦

**Comment by jiajing73** [comment]
题库错误率太高了，希望大神能对维护题库，答题争上游用这个总是错拿不到分。

**Comment by Ivan-cn** [comment]
那是挑战答题的控件位置和id变化了，改一下就可以了

**Comment by szsyzx** [comment]
@Ivan-cn 问题不会改啊

**Comment by jiajing73** [comment]
网络题库也不能更新了

**Comment by Ivan-cn** [comment]
> @Ivan-cn 问题不会改啊

我fork了部分代码，主要xxqg_v3.1.3(fix).js的839-842行：
while (!textContains("我要答题").exists());
    delay(1);
    click("我要答题");
    className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();

**Comment by szsyzx** [comment]
@Ivan-cn 兄弟你改的可以用了啊

**Comment by szsyzx** [comment]
@Ivan-cn 这个js用什么软件打开啊无语了

**Comment by Ivan-cn** [comment]
> @Ivan-cn 兄弟你改的可以用了啊

题库还不知道怎么回事。。。@lolisaikou

**Comment by szsyzx** [comment]
@Ivan-cn 兄弟xxqg_v3.1.3(fix).js怎么打开编辑啊

**Comment by nickyleu** [comment]
> > @Ivan-cn 问题不会改啊
> 
> 我fork了部分代码，主要xxqg_v3.1.3(fix).js的839-842行：
> while (!textContains("我要答题").exists());
> delay(1);
> click("我要答题");
> className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();

手机路径在哪里，我找不到

**Comment by szsyzx** [comment]
@Ivan-cn 路径我找到了，但是打开js都是乱码 请问你如何修改的兄弟 或者你帮修改好的js发一份谢谢

**Comment by nickyleu** [comment]
手机路径能说下么，我没找到

**Comment by szsyzx** [comment]
用MT管理器打开app在/assets/project下

**Comment by Ivan-cn** [comment]
=

> @Ivan-cn 这个js用什么软件打开啊无语了

auto.js，你可以下载来编译为apk啊，或等楼主修复题库的bug，好像题库也下载不了了。

> 用MT管理器打开app在/assets/project下

下载源码，用auto.js运行或重新编译啊，我说的是源代码，不是编译好的apk

**Comment by Ivan-cn** [comment]
> 手机路径能说下么，我没找到

下载源码，用auto.js运行或重新编译啊，我说的是源代码，不是编译好的apk

**Comment by ZHAOFEGNSHUN** [comment]
求大佬更新啊 学习强国又更新了

**Comment by wwsoo** [comment]
> > @Ivan-cn 问题不会改啊
> 
> 我fork了部分代码，主要xxqg_v3.1.3(fix).js的839-842行：
> while (!textContains("我要答题").exists());
> delay(1);
> click("我要答题");
> className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();

源码里面没有xxqg_v3.1.3(fix).js,只有xxqg_v3.1.3.js.而且只有600多行

**Comment by Ivan-cn** [comment]
> > > @Ivan-cn 问题不会改啊
> > 
> > 
> > 我fork了部分代码，主要xxqg_v3.1.3(fix).js的839-842行：
> > while (!textContains("我要答题").exists());
> > delay(1);
> > click("我要答题");
> > className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();
> 
> 源码里面没有xxqg_v3.1.3(fix).js,只有xxqg_v3.1.3.js.而且只有600多行

我用onekey的分支（一键42分）的，你选分支啊，不是默认这个

**Comment by liangchaohua** [comment]
> > > > @Ivan-cn 问题不会改啊
> > > 
> > > 
> > > 我fork了部分代码，主要xxqg_v3.1.3(fix).js的839-842行：
> > > while (!textContains("我要答题").exists());
> > > delay(1);
> > > click("我要答题");
> > > className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();
> > 
> > 
> > 源码里面没有xxqg_v3.1.3(fix).js,只有xxqg_v3.1.3.js.而且只有600多行
> 
> 我用onekey的分支（一键42分）的，你选分支啊，不是默认这个

其实最好单纯出个js版本的。直接放进auto.js运行。不用apk...当然我只是建议

**Comment by szsyzx** [comment]
@lolisaikou 亲爱的老大赶紧更新啊

**Comment by jiajing73** [comment]
@Ivan-cn 您的tiku-autoupdate，怎么用啊，下载了不会用啊

**Comment by admin0008** [comment]
由于网络题库不能更新，上传了个人的 tiku.db，有需要的到我的fork仓库下载食用。

**Comment by wwsoo** [comment]
> > > > @Ivan-cn 问题不会改啊
> > > 
> > > 
> > > 我fork了部分代码，主要xxqg_v3.1.3(fix).js的839-842行：
> > > while (!textContains("我要答题").exists());
> > > delay(1);
> > > click("我要答题");
> > > className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();
> > 
> > 
> > 源码里面没有xxqg_v3.1.3(fix).js,只有xxqg_v3.1.3.js.而且只有600多行
> 
> 我用onekey的分支（一键42分）的，你选分支啊，不是默认这个

onekey的分支（一键42分）,这个哪里可以下载？？

**Comment by abc362** [comment]
有该好的没发我下 @Ivan-cn

**Comment by wwsoo** [comment]
> 由于网络题库不能更新，上传了个人的 tiku.db，有需要的到我的fork仓库下载食用。

你那个怎么用手机下载.最好是打包的源码？

**Comment by wwsoo** [comment]
> > > > @Ivan-cn 问题不会改啊
> > > 
> > > 
> > > 我fork了部分代码，主要xxqg_v3.1.3(fix).js的839-842行：
> > > while (!textContains("我要答题").exists());
> > > delay(1);
> > > click("我要答题");
> > > className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();
> > 
> > 
> > 源码里面没有xxqg_v3.1.3(fix).js,只有xxqg_v3.1.3.js.而且只有600多行
> 
> 我用onekey的分支（一键42分）的，你选分支啊，不是默认这个

你说的分支在哪下载？？手机端怎么打包下？

**Comment by yanxi2018** [comment]
> 
> 
> 一个ºc±c½c»e¢一º一¸e½æ´æ°我¼一¸¼一º一¸ª一ººctiku.dbi¼æee¦c一°æcforka»º一¸e½½e£c¨一

如何将你的更新的打包进apk里面？  应该如何操作，请大神帮忙。

**Comment by abc362** [comment]
@Ivan-cn  我不会修改你有没有修改好的打包软件分享下

**Comment by admin0008** [comment]
> > 一个ºc�±�c½�c»�e¢�一º�一¸�e�½æ�´æ�°我¼�一¸�¼一º�一¸ª一ººc��tiku.dbi¼�æ��e��e¦�c��一�°æ��c��forka»�º�一¸�e½½e£�c�¨一��
> 
> 如何将你的更新的打包进apk里面？ 应该如何操作，请大神帮忙。

直接打包成apk了，链接如下
：https://github.com/admin0008/LazyStudy

**Comment by admin0008** [comment]
> @Ivan-cn 我不会修改你有没有修改好的打包软件分享下

可以试试我fork的版本
下载地址：https://github.com/admin0008/LazyStudy

**Comment by lolisaikou** [comment]
最近开学有点忙，题库是因为源的问题，无法更新了，我现在只能保留最后一个完整的版本
答题页面改版，改一行就能正常使用，
但是我看了 @admin0008 给我提交的 pr #51 ，感觉写的非常好，不过合并可能需要一点时间

**Comment by lolisaikou** [comment]
我先发一个版本，让大家能正常使用，然后再合并 @admin0008 的代码

**Comment by ZHAOFEGNSHUN** [comment]
谢谢大佬------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;lolisaikou&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月13日(星期天) 晚上10:58
收件人:&nbsp;&quot;lolisaikou/LazyStudy&quot;<LazyStudy@noreply.github.com&gt;;
抄送:&nbsp;&quot;ZHAOFEGNSHUN&quot;<1483000138@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lolisaikou/LazyStudy] 学习强国我要答题布局改变，导致软件卡在这里 (#52)
