### ISSUE TITLE
最近改版后不行了呀，一键42都不管用了。

### ISSUE THREAD

**Issue by arcqiufeng** [lolisaikou/LazyStudy#53]
4.6.9

错误描述：如题。

**Comment by admin0008** [comment]
我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。

我的一键57分，完美运行。

**Comment by Dr8pus** [comment]
> 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> 
> 我的一键57分，完美运行。

请问，一直往下翻页，显示没有当天的文章是什么情况啊

**Comment by admin0008** [comment]
> > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > 我的一键57分，完美运行。
> 
> 请问，一直往下翻页，显示没有当天的文章是什么情况啊

我也不知道你用的那个版本？

**Comment by abc362** [comment]
怎么修改不会啊 @admin0008

**Comment by Ivan-cn** [comment]
我fork了部分代码，主要xxqg_v3.1.3(fix).js的839-842行：
while (!textContains("我要答题").exists());
delay(1);
click("我要答题");
className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();

一键42正常使用啊，选patch2

**Comment by Ivan-cn** [comment]
> 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> 
> 我的一键57分，完美运行。

怎么一键57分？master分支也没有答题啊，要手动啊？

**Comment by Dr8pus** [comment]
> > > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > > 我的一键57分，完美运行。
> > 
> > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> 
> 我也不知道你用的那个版本？

![Screenshot_20200911_130521.jpg](https://user-images.githubusercontent.com/65865633/92864368-a0678300-f42f-11ea-9d18-3a64d85d5fb0.jpg)
这个

**Comment by admin0008** [comment]
我fork的打包了个apk：[https://github.com/admin0008/LazyStudy](url)

**Comment by admin0008** [comment]
> > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > 我的一键57分，完美运行。
> 
> 请问，一直往下翻页，显示没有当天的文章是什么情况啊

我fork的打包了个apk：https://github.com/admin0008/LazyStudy

**Comment by yanxi2018** [comment]
> 
> 
> > > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > > 我的一键57分，完美运行。
> > 
> > 
> > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> 
> 我fork的打包了个apk：https://github.com/admin0008/LazyStudy

大神、非常感谢。

**Comment by abc362** [comment]
@admin0008  新分享的浏览一直显示…翻页…
无法正常使用，但是挑战答题每日答题正常

**Comment by maythegood** [comment]
> > > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > > 我的一键57分，完美运行。
> > 
> > 
> > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> 
> 我fork的打包了个apk：https://github.com/admin0008/LazyStudy

俺也一样 无限........翻页............

**Comment by admin0008** [comment]
> > > > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > > > 我的一键57分，完美运行。
> > > 
> > > 
> > > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> > 
> > 
> > 我fork的打包了个apk：https://github.com/admin0008/LazyStudy
> 
> 俺也一样 无限........翻页............

有截图吗，特别是日志的截图（我手机没出现这个情况，不能判断哪里出问题了）

**Comment by abc362** [comment]
我录制了bug屏幕，你看下
链接:https://pan.baidu.com/s/12ghzWgckeZioRLpiKsCDVA 提取码:l3hq
顺便问下这个是点击浏览一键完成吗?如果不是希望出一个，感谢 @admin0008

**Comment by admin0008** [comment]
> 我录制了bug屏幕，你看下
> 链接:[https://pan.baidu.com/s/12ghzWgckeZioRLpiKsCDVA 提取码:l3hq](https://pan.baidu.com/s/12ghzWgckeZioRLpiKsCDVA%C2%A0%E6%8F%90%E5%8F%96%E7%A0%81:l3hq)
> 顺便问下这个是点击浏览一键完成吗?如果不是希望出一个，感谢 @admin0008

已修复。请重新下载！[https://github.com/admin0008/LazyStudy](url)

**Comment by admin0008** [comment]
> > > > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > > > 我的一键57分，完美运行。
> > > 
> > > 
> > > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> > 
> > 
> > 我fork的打包了个apk：https://github.com/admin0008/LazyStudy
> 
> 俺也一样 无限........翻页............

已修复。请重新下载！https://github.com/admin0008/LazyStudy

**Comment by Ivan-cn** [comment]
> 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> 
> 我的一键57分，完美运行。

题库好像不能下载了，而且你的题库大很多哦，要把修改的地方放进一键的313，要不挑战无法找到答案。
好像题库还是较少，在挑战上游一条都找不到😅

**Comment by gg8760** [comment]
> > > > > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > > > > 我的一键57分，完美运行。
> > > > 
> > > > 
> > > > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> > > 
> > > 
> > > 我fork的打包了个apk：https://github.com/admin0008/LazyStudy
> > 
> > 
> > 俺也一样 无限........翻页............
> 
> 已修复。请重新下载！https://github.com/admin0008/LazyStudy

新版本视频的无限翻页还存在 卡住 换了两个手机都这样 求修复

**Comment by chongyadong** [comment]
我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
我的一键57分，完美运行。
请问，一直往下翻页，显示没有当天的文章是什么情况啊
我fork的打包了个apk：https://github.com/admin0008/LazyStudy
俺也一样 无限........翻页............
已修复。请重新下载！https://github.com/admin0008/LazyStudy

用打包的apk版本不会无限翻页，但是用2.6.9fix的源码运行，怎么改都是无限翻页

**Comment by yanxi2018** [comment]
> 
> 
> > > > > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > > > > 我的一键57分，完美运行。
> > > > 
> > > > 
> > > > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> > > 
> > > 
> > > 我fork的打包了个apk：https://github.com/admin0008/LazyStudy
> > 
> > 
> > 俺也一样 无限........翻页............
> 
> 已修复。请重新下载！https://github.com/admin0008/LazyStudy

已知问题：1，挑战答题不做题。 2视听学习翻页到最后，显示结束，也是不进行学习。

**Comment by Dr8pus** [comment]
> 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> 
> 我的一键57分，完美运行。

![Screenshot_20200912_164811.jpg](https://user-images.githubusercontent.com/65865633/92991621-ccf6ca00-f517-11ea-9d96-ec91dc83d3ad.jpg)
没有57啊

**Comment by admin0008** [comment]
> > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > 我的一键57分，完美运行。
> 
> ![Screenshot_20200912_164811.jpg](https://user-images.githubusercontent.com/65865633/92991621-ccf6ca00-f517-11ea-9d96-ec91dc83d3ad.jpg)
> 没有57啊

这个fork只是对懒人学习的master分支fork，一键57是fork原版的xxqg-help，更简单，因为就一个js文件，没有UI，不过没建仓库，没有发。

另外一键57，如果题库不准确，什么周答题，专项答题错了就没法回头了，不太建议永，一般就是一键40或42就够了，不过这版本没把答题加入到浏览里，因为懒呀，😂

**Comment by admin0008** [comment]
> 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> 我的一键57分，完美运行。
> 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> 我fork的打包了个apk：https://github.com/admin0008/LazyStudy
> 俺也一样 无限........翻页............
> 已修复。请重新下载！https://github.com/admin0008/LazyStudy
> 
> 用打包的apk版本不会无限翻页，但是用2.6.9fix的源码运行，怎么改都是无限翻页

我发现问题所在了，我源码用的是 稳定模式。
打包成apk后，使用不了稳定模式，造成打包后的app运行出现各种bug。

所以源码的话 请使用 稳定模式 运行。

另外打包版的部分bug已经修复，我没认真测过 ，你可以重新下载试试

**Comment by chongyadong** [comment]
> > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > 我的一键57分，完美运行。
> > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> > 我fork的打包了个apk：https://github.com/admin0008/LazyStudy
> > 俺也一样 无限........翻页............
> > 已修复。请重新下载！https://github.com/admin0008/LazyStudy
> > 用打包的apk版本不会无限翻页，但是用2.6.9fix的源码运行，怎么改都是无限翻页
> 
> 我发现问题所在了，我源码用的是 稳定模式。
> 打包aok，使用不了稳定模式，造成打包后的各项bug。
> 
> 所以源码的话 请使用 稳定模式 运行。
> 
> 另外打包版的部分bug已经修复，我没认真测过 ，你可以重新下载试试

请问，怎么用稳定模式运行？

**Comment by abc362** [comment]
fix3测试:1小米10安卓11视频翻页bug已经修复，可以到42分
2.黑鲨2，安卓9，浏览完文章后关闭电台-新闻联播后会卡界面，不下拉，如果手动处理后接下来视频会一直显示翻页和早上bug相同 @admin0008

**Comment by Ivan-cn** [comment]
> > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > 我的一键57分，完美运行。
> > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> > 我fork的打包了个apk：https://github.com/admin0008/LazyStudy
> > 俺也一样 无限........翻页............
> > 已修复。请重新下载！https://github.com/admin0008/LazyStudy
> > 用打包的apk版本不会无限翻页，但是用2.6.9fix的源码运行，怎么改都是无限翻页
> 
> 我发现问题所在了，我源码用的是 稳定模式。
> 打包成apk后，使用不了稳定模式，造成打包后的app运行出现各种bug。
> 
> 所以源码的话 请使用 稳定模式 运行。
> 
> 另外打包版的部分bug已经修复，我没认真测过 ，你可以重新下载试试

打包成源码可以音量上键停止，然后右上角设置为稳定模式，但无障碍和js一样，要重启。

一键42的分支正常运行啊，就改个挑战的入口，我fork的目前正常啊，现在就是题库源的问题，无法下载

**Comment by admin0008** [comment]
> > > 我没有fork一键分支的版本，把我fork的master分支中的challengeAnswer.js 里的对于内容替换一下就行了。
> > > 我的一键57分，完美运行。
> > > 请问，一直往下翻页，显示没有当天的文章是什么情况啊
> > > 我fork的打包了个apk：https://github.com/admin0008/LazyStudy
> > > 俺也一样 无限........翻页............
> > > 已修复。请重新下载！https://github.com/admin0008/LazyStudy
> > > 用打包的apk版本不会无限翻页，但是用2.6.9fix的源码运行，怎么改都是无限翻页
> > 
> > 
> > 我发现问题所在了，我源码用的是 稳定模式。
> > 打包成apk后，使用不了稳定模式，造成打包后的app运行出现各种bug。
> > 所以源码的话 请使用 稳定模式 运行。
> > 另外打包版的部分bug已经修复，我没认真测过 ，你可以重新下载试试
> 
> 打包成源码可以音量上键停止，然后右上角设置为稳定模式，但无障碍和js一样，要重启。
> 
> 一键42的分支正常运行啊，就改个挑战的入口，我fork的目前正常啊，现在就是题库源的问题，无法下载

👍👍👍
