### ISSUE TITLE
最近改版了，答题部分的界面改变了，恳请大师修正

### ISSUE THREAD

**Issue by wwsongid** [lolisaikou/LazyStudy#54]
你的手机型号：荣耀20i

你的安卓版本：7

错误的截图：
https://ftp.bmp.ovh/imgs/2020/09/71d3cdd0d8ef0028.jpg
https://ftp.bmp.ovh/imgs/2020/09/d57ae94754f0cd23.jpg

错误描述：挑战答题那边就出错进行不下去

**Comment by admin0008** [comment]
可以试试我fork的版本
下载地址：https://github.com/admin0008/LazyStudy

**Comment by wwsongid** [comment]
谢谢大师，我是中学信息老师，跟你学徒吧？

在 2020-09-11 22:51:33，admin0008 <notifications@github.com> 写道：


可以试试我fork的版本
下载地址：https://github.com/admin0008/LazyStudy
