### ISSUE TITLE
更新网络题库报错

### ISSUE THREAD

**Issue by KB64ba** [lolisaikou/LazyStudy#55]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：
提示如下：
at file:///android_asset/modules/__json2__.js:505:0
    at updateTikunet ([remote]updateTikuNet.js:52:0)
    at [remote]updateTikuNet.js:63:0

这是什么问题

**Comment by admin0008** [comment]
这个真没办法，但可以试试我fork的版本，自带的题库算是正确率比较高。
下载地址：https://github.com/admin0008/LazyStudy

**Comment by nickyleu** [comment]
用了你上传更新的tiku.db和2.69fix版本的tiku.db，导入到一键42分版本中，现在挑战答题报错
https://ftp.bmp.ovh/imgs/2020/09/604f26d221a7deca.jpg

**Comment by admin0008** [comment]
你没合并好吧

**Comment by KB64ba** [comment]
> 你没合并好吧

var liArray = htmlArray.body.json(); 这段报错， 

我用auto4.1.1免费版， 不知道是否支持json解析，，
var htmlArray = http.get("https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json"); 好像是这段获取有问题还是什么

**Comment by admin0008** [comment]
> > 你没合并好吧
> 
> var liArray = htmlArray.body.json(); 这段报错，
> 
> 我用auto4.1.1免费版， 不知道是否支持json解析，，
> var htmlArray = http.get("https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json"); 好像是这段获取有问题还是什么

是的，在线题库问题，因为这页面已经打不开了。

**Comment by KB64ba** [comment]
> > > 你没合并好吧
> > 
> > 
> > var liArray = htmlArray.body.json(); 这段报错，
> > 我用auto4.1.1免费版， 不知道是否支持json解析，，
> > var htmlArray = http.get("https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json"); 好像是这段获取有问题还是什么
> 
> 是的，在线题库问题，因为这页面已经打不开了。

好的，谢谢，我还以为是我代码有问题呢！

**Comment by hanguowei98** [comment]
https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json
这个原来题库地址，可以用了，感谢@lolisaikou的更新和维护！

**Comment by haoguowei98** [comment]
各位大佬们，挑战答题正确率不是很高，有办法解决吗？咋个能更新tiku.db文件吗？
