### ISSUE TITLE
求大神更新，现在挑战答题和每日答题ui改版了

### ISSUE THREAD

**Issue by abc362** [lolisaikou/LazyStudy#56]

**Comment by admin0008** [comment]
可以试试我fork的版本
下载地址：https://github.com/admin0008/LazyStudy

**Comment by abc362** [comment]
新版存在重复收藏和不取消问题，无法浏览视频问题，问题截图https://imgchr.com/i/wU22eP
https://imgchr.com/i/wU2Rdf @admin0008

**Comment by admin0008** [comment]
早上更新了一下，fix3那个，因为我都源码js运行，没想到，打包竟会出这么多问题，哎！

**Comment by abc362** [comment]
lolisaikou求更新 @lolisaikou

**Comment by abc362** [comment]
求更新 @lolisaikou
