### ISSUE TITLE
大师，fork版本在订阅这块也进行不下去了

### ISSUE THREAD

**Issue by wwsongid** [lolisaikou/LazyStudy#57]
你的手机型号：荣耀20i

你的安卓版本：7

错误的截图：
https://ftp.bmp.ovh/imgs/2020/09/e81f55f8d7f9aebf.jpg

错误描述：
1.   fork版到订阅的地方就进行不了了，请大师出个新版
2   我是名中学信息老师，大师你那边收徒或团队队人不，我想加入你们，请大师你带带我

**Comment by admin0008** [comment]
老师，你好！
今天早上修复了一部分，可以重新下载测试。
我也是小白啊，现在才知道在autojs里源码运行没问题的，打包apk后，竟那么多问题，要修复，真废功夫，每改一点都要打包运行才能测试，头都大了。

**Comment by gg8760** [comment]
> 老师，你好！
> 今天早上修复了一部分，可以重新下载测试。
> 我也是小白啊，现在才知道在autojs里源码运行没问题的，打包apk后，竟那么多问题，要修复，真废功夫，每改一点都要打包运行才能测试，头都大了。

大神 你的最新版本能做个一键57或者42吗 目前的不包括答题部分 只有30分

**Comment by lolisaikou** [comment]
暂时不考虑建立团队，需要贡献代码的话可以提issue和pr，我都会认真看的
