### ISSUE TITLE
在推荐不停的翻页

### ISSUE THREAD

**Issue by tspine** [lolisaikou/LazyStudy#58]
我的订阅完成后就跳到推荐页面。然后就不停的在翻页。并没有进入文章学习。我没用apk的包。请问大师是怎么回事啊

**Comment by admin0008** [comment]
需要打开稳定模式！请自行在autojs设置界面设置

**Comment by KB64ba** [comment]
> 需要打开稳定模式！请自行在autojs设置界面设置
@admin0008 
var news_obj = text(s).depth(25).findOnce(t); 能帮我改下这个视频浏览换在“第一频道”怎么写了， 我不太懂用层次代码
——————————————————
还有可以在文章、视频（有多个月份的视频选项的）加个判断
date_string这个获取到年月就可以了，当翻到上个月就结束翻页，这就不用继续翻页
        if(textContains(date_string).exists())//当前页面上个月新闻
        {
            log("已经翻页到上个月，结束浏览……");
            vCount = vCount - i;
            return false;
        }

——————————————————
还可以在进行阅读文章时加这个

while (myScores['阅读文章'] != 6 || myScores["文章时长"] != 6  ) {
        var x = 0;
        articleStudyH( );//学习文章，包含点赞、分享和评论
        //console.info("等待十秒，然后确认文章是否已满分。");
        delay(0.5);
        x++;
        delay(2);
        console.info("检查阅读文章是否满分！")
        myScores = getScores(1);//获取积分，getScores(1)这个加不加1都可以，
        if (aCount != 0 ) {
            //aCount = Math.ceil((12 - myScores["我要选读文章"]+1) / 2); //文章个数
            console.log("还需要补阅读：" + aCount.toString() + "篇！");
        }else{
            console.info("已满分！");
            break;
        }
        if (x > 2) {//尝试三次
            console.info("尝试3次未满分，暂时跳过。");
            break;
        }
    }
