### ISSUE TITLE
能不能功能合并

### ISSUE THREAD

**Issue by zhq111** [lolisaikou/LazyStudy#6]
大神，2.6.2运行没有什么问题，不知道能不能合并功能，一键刷分。

**Comment by lolisaikou** [comment]
好建议会做的

**Comment by 85524365** [comment]
说出了大家心中的愿望，大神辛苦啦

**Comment by lolisaikou** [comment]
已经放在[分支](https://github.com/lolisaikou/LazyStudy/tree/onekey)上了，以后会上两个版本
这里[下载](https://github.com/lolisaikou/LazyStudy/releases)
