### ISSUE TITLE
【更新解决方法】根据评论老哥fork版本修改一个代码就行

### ISSUE THREAD

**Issue by Muyanglaw** [lolisaikou/LazyStudy#60]
普通版本是没问题的，就是一键42分版本在挑战答题部分找不到按钮，会停止运行。下载一键42分的全部代码
https://github.com/lolisaikou/LazyStudy/tree/onekey

打开 xxqg_v3.1.3(fix).js，找到 挑战答题的代码
function challengeQuestion() {
    text("我的").click();
    while (!textContains("我要答题").exists());
    delay(1);
    click("我要答题");
    **while (!text("答题竞赛").exists());**
    delay(1);
   **var ob= text("答题竞赛").findOne().parent();
    var index = ob.childCount() - 1;
    ob.child(index).click();
    console.info("开始挑战答题")**

修改的就加粗部分，修改好就可以了，从auto.js运行就行了，作者应该是忙，没看到大家反馈，大家可以先自行修改下用着。感谢提供fork版本的老哥

**Comment by liangchaohua** [comment]
运行那个

> 普通版本是没问题的，就是一键42分版本在挑战答题部分找不到按钮，会停止运行。下载一键42分的全部代码
> https://github.com/lolisaikou/LazyStudy/tree/onekey
> 
> 打开 xxqg_v3.1.3(fix).js，找到 挑战答题的代码
> function challengeQuestion() {
> text("我的").click();
> while (!textContains("我要答题").exists());
> delay(1);
> click("我要答题");
> **while (!text("答题竞赛").exists());**
> delay(1);
> **var ob= text("答题竞赛").findOne().parent(); var index = ob.childCount() - 1; ob.child(index).click(); console.info("开始挑战答题")**
> 
> 修改的就加粗部分，修改好就可以了，从auto.js运行就行了，作者应该是忙，没看到大家反馈，大家可以先自行修改下用着。感谢提供fork版本的老哥

谢谢老哥

**Comment by Ivan-cn** [comment]
我fork的就是onekey的，当时就直接改了能用

while (!textContains("我要答题").exists());
delay(1);
click("我要答题");
className("android.view.View").text("每日答题").findOne().parent().parent().child(10).click();

原理都是一样的，相对的方式找控件

**Comment by yanxi2018** [comment]
> 
> 
> 普通版本是没问题的，就是一键42分版本在挑战答题部分找不到按钮，会停止运行。下载一键42分的全部代码
> https://github.com/lolisaikou/LazyStudy/tree/onekey
> 
> 打开 xxqg_v3.1.3(fix).js，找到 挑战答题的代码
> function challengeQuestion() {
> text("我的").click();
> while (!textContains("我要答题").exists());
> delay(1);
> click("我要答题");
> **while (!text("答题竞赛").exists());**
> delay(1);
> **var ob= text("答题竞赛").findOne().parent(); var index = ob.childCount() - 1; ob.child(index).click(); console.info("开始挑战答题")**
> 
> 修改的就加粗部分，修改好就可以了，从auto.js运行就行了，作者应该是忙，没看到大家反馈，大家可以先自行修改下用着。感谢提供fork版本的老哥

只需要在auto.js里面运行这一个js就可以吗？一直使用的apk，这个没了解过

**Comment by Muyanglaw** [comment]
> > 普通版本是没问题的，就是一键42分版本在挑战答题部分找不到按钮，会停止运行。下载一键42分的全部代码
> > https://github.com/lolisaikou/LazyStudy/tree/onekey
> > 打开 xxqg_v3.1.3(fix).js，找到 挑战答题的代码
> > function challengeQuestion() {
> > text("我的").click();
> > while (!textContains("我要答题").exists());
> > delay(1);
> > click("我要答题");
> > **while (!text("答题竞赛").exists());**
> > delay(1);
> > **var ob= text("答题竞赛").findOne().parent(); var index = ob.childCount() - 1; ob.child(index).click(); console.info("开始挑战答题")**
> > 修改的就加粗部分，修改好就可以了，从auto.js运行就行了，作者应该是忙，没看到大家反馈，大家可以先自行修改下用着。感谢提供fork版本的老哥
> 
> 只需要在auto.js里面运行这一个js就可以吗？一直使用的apk，这个没了解过

不是，全部都需要，直接放到 脚本 文件夹里，跟一个程序一样

**Comment by arcqiufeng** [comment]
auto.js是在哪里下载？我在应用商店里面没有找到，这是一个单独的应用程序吗？是一个apk吗？
