### ISSUE TITLE
原来获取题库的地址是不是挂了?

### ISSUE THREAD

**Issue by Lee-20** [lolisaikou/LazyStudy#61]
http://49.235.90.76:5000/
好像进不去了

**Comment by lolisaikou** [comment]
是的，我这里有留下最后一个完整的[json版本](https://github.com/lolisaikou/tiku-autoupdate)
因为这个题库不是我维护的，所以我也不知道最后发生了什么。

**Comment by Lee-20** [comment]
> 是的，我这里有留下最后一个完整的[json版本，](https://github.com/lolisaikou/tiku-autoupdate)
> 因为这个题库不是我维护的，所以我也不知道最后发生了什么。

不知道他之前是怎么更新题库的。
我现在除了用脚本去答每日硬刷题库，不知道还有啥方法。
尤其是挑战答题，现在出了字形题制裁题库，感觉数据库相关的代码要做很多改动才能应对。

**Comment by lolisaikou** [comment]
主要是挑战答题捕获正确答案有点麻烦，每日只能硬刷

**Comment by Lee-20** [comment]
> 主要是挑战答题捕获正确答案有点麻烦，每日只能硬刷

我现在就在硬刷每日，但是它保存的答案是ABCD型的，感觉不太好。
挑战答题设置的是题库里没有的，就随机选，选对了就保存。如果专门为了刷题库的话，是不是可以考虑加上搜索啥的。
字形题再做特殊应对。

**Comment by nickyleu** [comment]
题库更新貌似自己手动还不行，我昨天试了，手动加进去貌似不可以，不知道什么逻辑
另外为什么题库有的，答案也是对的，答题还是错的呢，有的题会在tikunet找，那个答案和题库个别也不一样
不知道有什么能更新题库的好方法

**Comment by jw8013** [comment]
> 主要是挑战答题捕获正确答案有点麻烦，每日只能硬刷

https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json
这个网页也同原网站一起炸了？
File size exceeded the configured limit of 20 MB.

**Comment by Tongzhao9417** [comment]
有一个兔子答题，里面的题库正确率还是比较高的。只不过这个兔子答题识别题目总出错。要不我把文件发上来您研究一下？

**Comment by KB64ba** [comment]
> 有一个兔子答题，里面的题库正确率还是比较高的。只不过这个兔子答题识别题目总出错。要不我把文件发上来您研究一下？

发个题库文件看看，

**Comment by Tongzhao9417** [comment]
> > 有一个兔子答题，里面的题库正确率还是比较高的。只不过这个兔子答题识别题目总出错。要不我把文件发上来您研究一下？
> 
> 发个题库文件看看，

[兔子答题_v1.0.3.zip](https://github.com/lolisaikou/LazyStudy/files/5215875/_v1.0.3.zip)
不会发题库，发apk吧

**Comment by Ivan-cn** [comment]
> 是的，我这里有留下最后一个完整的[json版本](https://github.com/lolisaikou/tiku-autoupdate)
> 因为这个题库不是我维护的，所以我也不知道最后发生了什么。

https://github.com/isysc1/Xxqg

这有个项目，页面能搜到题，但不知能转换适用的题库否。

**Comment by KB64ba** [comment]
> > > 有一个兔子答题，里面的题库正确率还是比较高的。只不过这个兔子答题识别题目总出错。要不我把文件发上来您研究一下？
> > 
> > 
> > 发个题库文件看看，
> 
> [兔子答题_v1.0.3.zip](https://github.com/lolisaikou/LazyStudy/files/5215875/_v1.0.3.zip)
> 不会发题库，发apk吧
https://lei999.lanzoui.com/b00zt9vxi 题库已经提取出来了，

**Comment by Ivan-cn** [comment]
> > > > 有一个兔子答题，里面的题库正确率还是比较高的。只不过这个兔子答题识别题目总出错。要不我把文件发上来您研究一下？
> > > 
> > > 
> > > 发个题库文件看看，
> > 
> > 
> > [兔子答题_v1.0.3.zip](https://github.com/lolisaikou/LazyStudy/files/5215875/_v1.0.3.zip)
> > 不会发题库，发apk吧
> > https://lei999.lanzoui.com/b00zt9vxi 题库已经提取出来了，

怎么我解开才2.88m，你解的有8m这么大？
看界面，这兔子应该和这个基本一样

**Comment by hanguowei98** [comment]
https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json
这个原来题库地址，可以用了，感谢@lolisaikou的更新和维护！

**Comment by KB64ba** [comment]
> > > > > 有一个兔子答题，里面的题库正确率还是比较高的。只不过这个兔子答题识别题目总出错。要不我把文件发上来您研究一下？
> > > > 
> > > > 
> > > > 发个题库文件看看，
> > > 
> > > 
> > > [兔子答题_v1.0.3.zip](https://github.com/lolisaikou/LazyStudy/files/5215875/_v1.0.3.zip)
> > > 不会发题库，发apk吧
> > > https://lei999.lanzoui.com/b00zt9vxi 题库已经提取出来了，
> 
> 怎么我解开才2.88m，你解的有8m这么大？
> 看界面，这兔子应该和这个基本一样

这个是合并最大的两个库了

**Comment by KB64ba** [comment]
> https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json
> 这个原来题库地址，可以用了，感谢@lolisaikou的更新和维护！

最新最后的更新地址就是这个， 只是前几天临时关闭，现在又开了

**Comment by haoguowei98** [comment]
各位大佬们，挑战答题正确率不是很高，有办法解决吗？咋个能更新tiku.db文件吗？

**Comment by KB64ba** [comment]
> 各位大佬们，挑战答题正确率不是很高，有办法解决吗？咋个能更新tiku.db文件吗？

[https://ftp.bmp.ovh/imgs/2020/09/85aa907a25bf26a8.jpg](url)

Navicat 12 for SQLite

**Comment by tq036my** [comment]
为防止失联，建议可以设计为自定义题库更新地址，并且可以自己编辑上传自己的题库。
