### ISSUE TITLE
分享个挑战答题题库，更新至2106题（更新时间2020年9月12日）

### ISSUE THREAD

**Issue by hanguowei98** [lolisaikou/LazyStudy#62]
挑战答题题链接：https://github.com/ztianming/xuexi.cn

**Comment by nickyleu** [comment]
主要是tiku.db这个文件不会编辑，最近挑战答题的题库在更新，有删有加，每天题库数都不一样，我现在用1529的题库练习记忆，因为有比赛

**Comment by haoguowei98** [comment]
我把自己将就刷的tiku.db分享出来，挑战答题正确率还是比较可以！https://wwa.lanzous.com/iQa5egrs7ra

**Comment by nickyleu** [comment]
谢谢分享，我看文件才3.2MB，好像和打包文件差不多大小，上个帖子有分享出来的8.17MB

**Comment by hanguowei98** [comment]
这个可能软件把它压缩了吧，我也不是很懂，自己摸索搞的，还是希望有能力的大神来很好的来更新了！

**Comment by Ivan-cn** [comment]
> 这个可能软件把它压缩了吧，我也不是很懂，自己摸索搞的，还是希望有能力的大神来很好的来更新了！

那个8M的很多空数据，实际上题库并不多，特别是tiku表才1000多条；

你的这个tikunet表比较多，有8290条，在线更新的才7878条，多谢分享。

**Comment by hanguowei98** [comment]
我分享的那个tiku.db，在tikunet表中重复的还是比较多，由于能力有限只做了简单的手工添加，望有能力、有空的前辈和大神来更新了，然后再分享出来，谢谢！

**Comment by nickyleu** [comment]
> > 这个可能软件把它压缩了吧，我也不是很懂，自己摸索搞的，还是希望有能力的大神来很好的来更新了！
> 
> 那个8M的很多空数据，实际上题库并不多，特别是tiku表才1000多条；
> 
> 你的这个tikunet表比较多，有8290条，在线更新的才7878条，多谢分享。

能看到明细啊，用什么软件看的，可以编辑吗？

**Comment by haoguowei98** [comment]
DB.Browser.for.SQLite-3.12.0：https://wwa.lanzous.com/iAg19gt9mub

**Comment by nickyleu** [comment]
> DB.Browser.for.SQLite-3.12.0：https://wwa.lanzous.com/iAg19gt9mub

谢谢，终于可以看到编辑明细了
现在有个问题，题库中有的题目，为啥有的时候找不到呢？查找完我发现tiku和tikunet都有，而且 有重复，或者答案不一样，不知道是不是这个原因造成的

**Comment by haoguowei98** [comment]
> > DB.Browser.for.SQLite-3.12.0：https://wwa.lanzous.com/iAg19gt9mub
> 
> 谢谢，终于可以看到编辑明细了
> 现在有个问题，题库中有的题目，为啥有的时候找不到呢？查找完我发现tiku和tikunet都有，而且 有重复，或者答案不一样，不知道是不是这个原因造成的

还有款软件可以打开编辑，navicat for sqlite 12.1.7破解版：https://wwa.lanzous.com/iPqlcgtj7sj

**Comment by hanguowei98** [comment]
> > > DB.Browser.for.SQLite-3.12.0：https://wwa.lanzous.com/iAg19gt9mub
> > 
> > 
> > 谢谢，终于可以看到编辑明细了
> > 现在有个问题，题库中有的题目，为啥有的时候找不到呢？查找完我发现tiku和tikunet都有，而且 有重复，或者答案不一样，不知道是不是这个原因造成的
> 
> 还有款软件可以打开编辑，navicat for sqlite 12.1.7破解版：https://wwa.lanzous.com/iPqlcgtj7sj

补个安装navicat for sqlite 12.1.7破解版教程链接：https://blog.csdn.net/cungudafa/article/details/84674811

**Comment by Muyanglaw** [comment]
> 我把自己将就刷的tiku.db分享出来，挑战答题正确率还是比较可以！https://wwa.lanzous.com/iQa5egrs7ra

感谢，这个题库好多了

**Comment by nickyleu** [comment]
answer from char=
这个答案在哪修改，tiku文件找不到，有部分错误的

**Comment by haoguowei98** [comment]
> answer from char=
> 这个答案在哪修改，tiku文件找不到，有部分错误的
选择词语正确的词形。这种题在题库中的答案就只能A或B，你们发展没？
较新的db题库：https://www.lanzoui.com/icl82gwielg

**Comment by KB64ba** [comment]
> answer from char=
> 这个答案在哪修改，tiku文件找不到，有部分错误的

tiku文件现在有两个表（tiku、tikuNet），两个表都要查询的

**Comment by nickyleu** [comment]
> > answer from char=
> > 这个答案在哪修改，tiku文件找不到，有部分错误的
> 
> tiku文件现在有两个表（tiku、tikuNet），两个表都要查询的

我知道有2个啊，比如选择词语的正确词性，两个表里面你搜索不出来的，答题会显示answer from char=   ，有的是错误的，然后我在tiku文件已经全部添加了正确的题库，做题没啥用，所以想知道显示answer from char=  是从哪搜出来的答案，这个怎么解

**Comment by hanguowei98** [comment]
> > > answer from char=
> > > 这个答案在哪修改，tiku文件找不到，有部分错误的
> > 
> > 
> > tiku文件现在有两个表（tiku、tikuNet），两个表都要查询的
> 
> 我知道有2个啊，比如选择词语的正确词性，两个表里面你搜索不出来的，答题会显示answer from char= ，有的是错误的，然后我在tiku文件已经全部添加了正确的题库，做题没啥用，所以想知道显示answer from char= 是从哪搜出来的答案，这个怎么解

“选择词语的正确词性。”可能题目一样，无法识别正确的答案，所以手动加答案是没有用的，答案只能识别A或B，这种情况可能只有作者和各位有能力的大神来修改优化代码了！

**Comment by nickyleu** [comment]
> > > > answer from char=
> > > > 这个答案在哪修改，tiku文件找不到，有部分错误的
> > > 
> > > 
> > > tiku文件现在有两个表（tiku、tikuNet），两个表都要查询的
> > 
> > 
> > 我知道有2个啊，比如选择词语的正确词性，两个表里面你搜索不出来的，答题会显示answer from char= ，有的是错误的，然后我在tiku文件已经全部添加了正确的题库，做题没啥用，所以想知道显示answer from char= 是从哪搜出来的答案，这个怎么解
> 
> “选择词语的正确词性。”可能题目一样，无法识别正确的答案，所以手动加答案是没有用的，答案只能识别A或B，这种情况可能只有作者和各位有能力的大神来修改优化代码了！

你的意思，这部分现在还是属于随机点？
可能我碰到同类题比较多，觉得错误的总是那几个词

**Comment by hanguowei98** [comment]
你们用这个db题库嘛，比上次分享的好很多了，自己用反正觉得错误很少！https://www.lanzoui.com/icl82gwielg

**Comment by nickyleu** [comment]
> 你们用这个db题库嘛，比上次分享的好很多了，自己用反正觉得错误很少！https://www.lanzoui.com/icl82gwielg

解开看了下，和上次那个大变样，我在测试下，上次那个里面重复和错误的很多，我还在抽空修正和添加题目

还有个问题就是题库里面有，但是搜索不出来，不知道什么原因

**Comment by adamnb1** [comment]
> 谢谢分享，我看文件才3.2MB，好像和打包文件差不多大小，上个帖子有分享出来的8.17MB

弱弱问一下，一健42分版题库文件放哪个路径？
