### ISSUE TITLE
挑战答题这个错误代码什么意思

### ISSUE THREAD

**Issue by nickyleu** [lolisaikou/LazyStudy#63]
错误的截图：
<img src = 'https://ftp.bmp.ovh/imgs/2020/09/206098ec211f7091.jpg' />

在Autojs打开，下载的2.7，打开是还是2.69

**Comment by Ivan-cn** [comment]
选了onekey 的分支了没有，

一键42分版：
https://codeload.github.com/lolisaikou/LazyStudy/zip/onekey

**Comment by nickyleu** [comment]
我还是觉得是题库文件问题，一个题重复录入好像就有这个问题

**Comment by haoguowei98** [comment]
> 我还是觉得是题库文件问题，一个题重复录入好像就有这个问题

优化后的db题库：https://www.lanzoui.com/icl82gwielg

**Comment by hanguowei98** [comment]
> 我还是觉得是题库文件问题，一个题重复录入好像就有这个问题

选择词语正确的词形。这种题在题库中的答案就只能A或B，你们发现没？
较新的db题库：https://www.lanzoui.com/icl82gwielg

**Comment by nickyleu** [comment]
> > 我还是觉得是题库文件问题，一个题重复录入好像就有这个问题
> 
> 选择词语正确的词形。这种题在题库中的答案就只能A或B，你们发现没？
> 较新的db题库：https://www.lanzoui.com/icl82gwielg

谢谢，我一直再用你上一版的更新中
选择词语的正确词形，我已经全部添加进tiku.db，但是实际答题的时候，好像还是从网络选择错误的，answer from char，这个就不会修改了
