### ISSUE TITLE
强国积分规则又改了，求各位大佬完善！感谢！

### ISSUE THREAD

**Issue by haoguowei98** [lolisaikou/LazyStudy#65]

**Comment by 1130078044** [comment]
这次不能更吧，以前相当于单机游戏，你怎么学都是你自己的事，软件只是帮你学而已，再高级的软件一天最多也就和别人学的分一样多。现在相当于网络游戏，这等于开外挂，如果更新了官方肯定加大追查力度，作者也倒霉，用的也倒霉。作者可能被现实制裁，用的人可能被封号，一天就那几分，有必要吗

**Comment by 1130078044** [comment]
> 这次不能更吧，以前相当于单机游戏，你怎么学都是你自己的事，软件只是帮你学而已，再高级的软件一天最多也就和别人学的分一样多。现在相当于网络游戏，这等于开外挂，如果更新了官方肯定加大追查力度，作者也倒霉，用的也倒霉。作者可能被现实制裁，用的人可能被封号，一天就那几分，有必要吗

就像玩王者，你用脚本刷冒险模式一样，就是刷金币而已，每周有上限的，你怎么刷最多就那么多，无非是自己省事了。
如果对战模式你开个透视，开个守约自描，已经影响到别人了，官方绝对狠查，稳定还是比较重要的。

**Comment by lovelyjunya** [comment]
应该只能加一个争上游答题功能，一键42分改不了，不过估计也挺麻烦，没题库，答题部分代码也要改。得大神研究下，至于双人对战就只能手动了，注册一个小号，先答小号再答大号，大号肯定能得2分。

**Comment by xiezm** [comment]
安卓怎么安装

**Comment by haoguowei98** [comment]
> > 这次不能更吧，以前相当于单机游戏，你怎么学都是你自己的事，软件只是帮你学而已，再高级的软件一天最多也就和别人学的分一样多。现在相当于网络游戏，这等于开外挂，如果更新了官方肯定加大追查力度，作者也倒霉，用的也倒霉。作者可能被现实制裁，用的人可能被封号，一天就那几分，有必要吗
> 
> 就像玩王者，你用脚本刷冒险模式一样，就是刷金币而已，每周有上限的，你怎么刷最多就那么多，无非是自己省事了。
> 如果对战模式你开个透视，开个守约自描，已经影响到别人了，官方绝对狠查，稳定还是比较重要的。

@1130078044  可以不更新，已找到其他工具来答争上游答题和双人对战！

**Comment by wwsoo** [comment]
> > > 这次不能更吧，以前相当于单机游戏，你怎么学都是你自己的事，软件只是帮你学而已，再高级的软件一天最多也就和别人学的分一样多。现在相当于网络游戏，这等于开外挂，如果更新了官方肯定加大追查力度，作者也倒霉，用的也倒霉。作者可能被现实制裁，用的人可能被封号，一天就那几分，有必要吗
> > 
> > 
> > 就像玩王者，你用脚本刷冒险模式一样，就是刷金币而已，每周有上限的，你怎么刷最多就那么多，无非是自己省事了。
> > 如果对战模式你开个透视，开个守约自描，已经影响到别人了，官方绝对狠查，稳定还是比较重要的。
> 
> @1130078044 可以不更新，已找到其他工具来答争上游答题和双人对战！

工具能分享一下吗？？

**Comment by admin0008** [comment]
看图不解释
![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

**Comment by nickyleu** [comment]
> > > 这次不能更吧，以前相当于单机游戏，你怎么学都是你自己的事，软件只是帮你学而已，再高级的软件一天最多也就和别人学的分一样多。现在相当于网络游戏，这等于开外挂，如果更新了官方肯定加大追查力度，作者也倒霉，用的也倒霉。作者可能被现实制裁，用的人可能被封号，一天就那几分，有必要吗
> > 
> > 
> > 就像玩王者，你用脚本刷冒险模式一样，就是刷金币而已，每周有上限的，你怎么刷最多就那么多，无非是自己省事了。
> > 如果对战模式你开个透视，开个守约自描，已经影响到别人了，官方绝对狠查，稳定还是比较重要的。
> 
> @1130078044 可以不更新，已找到其他工具来答争上游答题和双人对战！

其他工具都有了啊，牛，分享下

**Comment by nickyleu** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

新版本更新好了？ 自定义功能看着不错

**Comment by ID435858113** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

老大，这个工具能分享下嘛？

**Comment by lovelyjunya** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

分享一下呗，还打码呢

**Comment by haoguowei98** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

@ admin0008   赞👍，你这个高级！

**Comment by haoguowei98** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

@admin0008  赞👍，你这个高级！

**Comment by smiletianque** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

分享一下吧 老哥

**Comment by azxcf123** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

求分享

**Comment by lnxcyq** [comment]
早期版本的懒人有挑战提示的，好像

**Comment by nihaoyouqu** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

分享一下吧 大佬

**Comment by abc362** [comment]
求分享 @nickyleu

**Comment by nickyleu** [comment]
> 求分享 @nickyleu

我没有啊，我也在等新版本

**Comment by abc362** [comment]
求分享 @admin0008

**Comment by Ivan-cn** [comment]
> 看图不解释
> ![S00929-17235248(1)](https://user-images.githubusercontent.com/70740039/94540814-7d373300-0279-11eb-910e-ff56e952194c.png)
> ![S00929-17180756(1)](https://user-images.githubusercontent.com/70740039/94540839-845e4100-0279-11eb-9102-7f1dbca4a122.png)

这什么工具？分享一下一起学习不？

**Comment by admin0008** [comment]
双节来临，普天同庆！
把近一个月的更新，重构界面功能；不断更新题库；加入工具模式；

自定义学习：按照页面的开关选项和参数进行学习。 工具模式：不进行学习，只保留答题提示功能。可以在各种答题界面使用，如每日、每周、专项、挑战和竞答。但是在竞答中，只提示，不点击。 一键学习：按照获得的学分进行学习。为了避免专项答题失分（因为填空题不能保证全对），所以一键学习不会进行专项答题，即最多一键47分。 安装包下载

注：由于我没有升级xxqg的2.17的版本，所以2.17的用户请自己重新安装2.15版本的xxqg享用。

其实功能也就差不多了，不打算继续更新了，可能一下次更新是下个双节（我也不知道还会不会有双节）

**Comment by haoguowei98** [comment]
> 双节来临，普天同庆！
> 
> 更新了安装包，这个算是最终版了。
> 
> [下载请点击](https://github.com/admin0008/LazyStudy)
> 
> 注：由于我没有升级xxqg的2.17的版本，所以2.17的用户请自己重新安装2.15版本的xxqg享用。

@admin0008 感谢分享，辛苦了！

**Comment by abc362** [comment]
@admin0008  感谢大佬，祝大佬中秋节快乐，然后我这个软件不能用🌚我点开后会显示如下https://imgchr.com/i/0uhKoD手机系统安卓11，我童鞋的不是安卓11正常

**Comment by admin0008** [comment]
> @admin0008 感谢大佬，祝大佬中秋节快乐，然后我这个软件不能用🌚我点开后会显示如下[https://imgchr.com/i/0uhKoD手机系统安卓11，我童鞋的不是安卓11正常](https://imgchr.com/i/0uhKoD%E6%89%8B%E6%9C%BA%E7%B3%BB%E7%BB%9F%E5%AE%89%E5%8D%9311%EF%BC%8C%E6%88%91%E7%AB%A5%E9%9E%8B%E7%9A%84%E4%B8%8D%E6%98%AF%E5%AE%89%E5%8D%9311%E6%AD%A3%E5%B8%B8)

系统版本差也许，我也测试不了，另外图床不行啊，看不到图

**Comment by admin0008** [comment]
> @admin0008 感谢大佬，祝大佬中秋节快乐，然后我这个软件不能用🌚我点开后会显示如下[https://imgchr.com/i/0uhKoD手机系统安卓11，我童鞋的不是安卓11正常](https://imgchr.com/i/0uhKoD%E6%89%8B%E6%9C%BA%E7%B3%BB%E7%BB%9F%E5%AE%89%E5%8D%9311%EF%BC%8C%E6%88%91%E7%AB%A5%E9%9E%8B%E7%9A%84%E4%B8%8D%E6%98%AF%E5%AE%89%E5%8D%9311%E6%AD%A3%E5%B8%B8)

看到你截图了，你试试先打开学习强国后，再返回运行。
因为我设置打开学习强国，然后等待4秒，进行后面操作，如果有些手机打开学习强国超4秒的话，可能就返回桌面了

**Comment by abc362** [comment]
这是视频，你看下链接：https://cowtransfer.com/s/c63a761308894a 或使用取件码：qehk3z
@admin0008

**Comment by admin0008** [comment]
> 这是视频，你看下链接：https://cowtransfer.com/s/c63a761308894a 或使用取件码：qehk3z
> @admin0008

你的是不是把学习强国升级了，我这个没适配最新的2.17版本。

**Comment by abc362** [comment]
是的，我刚发现自动更新了 @admin0008

**Comment by admin0008** [comment]
> 是的，我刚发现自动更新了 @admin0008

哦，请豌豆荚或者其他应用市场下载历史版本。

我一般不升级，因为我不清楚官方是否会在新版本加上反作弊的功能，所以还是不尝鲜，除非旧版本完全不能用再升。

**Comment by Ivan-cn** [comment]
> > 是的，我刚发现自动更新了 @admin0008
> 
> 哦，请豌豆荚或者其他应用市场下载历史版本。
> 
> 我一般不升级，因为我不清楚官方是否会在新版本加上反作弊的功能，所以还是不尝鲜，除非旧版本完全不能用再升。

有没有源码js的版本，我设置了auto.js自动运行脚本，且切换账号学习。。。所以想学习一下你的代码。

**Comment by chongyadong** [comment]
> 双节来临，普天同庆！
> 
> 更新了安装包，这个算是最终版了。
> 
> [下载请点击](https://github.com/admin0008/LazyStudy)
> 
> 注：由于我没有升级xxqg的2.17的版本，所以2.17的用户请自己重新安装2.15版本的xxqg享用。

同求大神上传js源码，不然2.17完全没法用

**Comment by KB64ba** [comment]
> 双节来临，普天同庆！
> 
> 更新了安装包，这个算是最终版了。
> 
> [下载请点击](https://github.com/admin0008/LazyStudy)
> 
> 注：由于我没有升级xxqg的2.17的版本，所以2.17的用户请自己重新安装2.15版本的xxqg享用。

同求大佬的源码 @admin0008

**Comment by wdqzgx** [comment]
> > > 是的，我刚发现自动更新了 @admin0008
> > 
> > 
> > 哦，请豌豆荚或者其他应用市场下载历史版本。
> > 我一般不升级，因为我不清楚官方是否会在新版本加上反作弊的功能，所以还是不尝鲜，除非旧版本完全不能用再升。
> 
> 有没有源码js的版本，我设置了auto.js自动运行脚本，且切换账号学习。。。所以想学习一下你的代码。

 @Ivan-cn 可不可以分享一下切换账号学习的源码

**Comment by haoguowei98** [comment]
> 双节来临，普天同庆！
> 
> 更新了安装包，这个算是最终版了。
> 
> [下载请点击](https://github.com/admin0008/LazyStudy)
> 
> 注：由于我没有升级xxqg的2.17的版本，所以2.17的用户请自己重新安装2.15版本的xxqg享用。

 @admin0008  分享下源码，感谢！

**Comment by haoguowei98** [comment]
> 双节来临，普天同庆！
> 
> 更新了安装包，这个算是最终版了。
> 
> [下载请点击](https://github.com/admin0008/LazyStudy)
> 
> 注：由于我没有升级xxqg的2.17的版本，所以2.17的用户请自己重新安装2.15版本的xxqg享用。

 @admin0008 再次感谢，麻烦分享下源码，代码不加密可以不？
