### ISSUE TITLE
大侠，强国大改版啊，咱们能更新吗？

### ISSUE THREAD

**Issue by adamnb1** [lolisaikou/LazyStudy#66]
大侠，强国大改版啊，咱们能更新吗？

**Comment by abc362** [comment]
@ LazyStudy

**Comment by abc362** [comment]
@LazyStudy

**Comment by annonen** [comment]
把所有的("学习")改成("工作")，以及function getScores(i) 里的
while (!id("我的").exists());//等待加载出主页
改成
while (!id("comm_head_xuexi_mine").exists());//等待加载出主页

**Comment by wwsoo** [comment]
> 把所有的("学习")改成("工作")，以及function getScores(i) 里的
> while (!id("我的").exists());//等待加载出主页
> 改成
> while (!id("comm_head_xuexi_mine").exists());//等待加载出主页

有没有成品？？

**Comment by forbbs** [comment]
text("工作") 的click 不行，没有效果
