### ISSUE TITLE
V2.17.0无法使用

### ISSUE THREAD

**Issue by aweder** [lolisaikou/LazyStudy#67]
你的手机型号：荣耀 30

你的安卓版本： 10

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：新版无法使用，一直停在等待加载主页

**Comment by Ivan-cn** [comment]
把所有的("学习")改成("工作")，42分专版（onekey）的通过。
