### ISSUE TITLE
开始浏览找不到/data/user/0/com.lazyxue.onekey/files/project/all.js文件

### ISSUE THREAD

**Issue by aweder** [lolisaikou/LazyStudy#7]
你的手机型号：华为Nova4

你的安卓版本：10

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：
08:20:35.322/E: Thread[ScriptThread-2[/data/user/0/com.lazyxue.onekey/files/project/floating.js] (Spawn-1),5]: Error: Module "/data/user/0/com.lazyxue.onekey/files/project/all.js" not found. (file:///android_asset/modules/jvm-npm.js#96)
Error: Module "/data/user/0/com.lazyxue.onekey/files/project/all.js" not found.
    at Require (file:///android_asset/modules/jvm-npm.js:96:0)
    at floating.js.js:93:0

**Comment by aweder** [comment]
查看了一下，一键44分版，主要是在floating.js这个文件中
//浏览
window.startLL.click(() => {
    let ss = "./all.js";
    startTh(ss);
});

**Comment by lolisaikou** [comment]
大意了，昨天没有测试，已经重新上传了

**Comment by aweder** [comment]
嗯，代码中已经改来了，更新一下APK吧，不然下载下来使用还是会报错！

**Comment by lolisaikou** [comment]
> 嗯，代码中已经改来了，更新一下APK吧，不然下载下来使用还是会报错！

apk也更新了啊

**Comment by jisu20162** [comment]
APP貌似没更新啊，还是报错。

**Comment by lolisaikou** [comment]
> APP貌似没更新啊，还是报错。

能不能上传一下报错的截图

**Comment by jisu20162** [comment]
> > APP貌似没更新啊，还是报错。
> 
> 能不能上传一下报错的截图
https://ftp.bmp.ovh/imgs/2020/07/dd784f561ffc824f.png
跟上面的错误一样的，找不到all.js。下载的最新2.6.2 44p.apk

**Comment by lolisaikou** [comment]
> > > APP貌似没更新啊，还是报错。
> > 
> > 
> > 能不能上传一下报错的截图
> > https://ftp.bmp.ovh/imgs/2020/07/dd784f561ffc824f.png
> > 跟上面的错误一样的，找不到all.js。下载的最新2.6.2 44p.apk

重新上传了，点[这里](https://github.com/lolisaikou/LazyStudy/releases/download/v2.6.2/Lazyxue_2.6.2_44p.apk)下载
我一直在用，不应该啊

**Comment by jisu20162** [comment]
> > > > APP貌似没更新啊，还是报错。
> > > 
> > > 
> > > 能不能上传一下报错的截图
> > > https://ftp.bmp.ovh/imgs/2020/07/dd784f561ffc824f.png
> > > 跟上面的错误一样的，找不到all.js。下载的最新2.6.2 44p.apk
> 
> 重新上传了，点[这里](https://github.com/lolisaikou/LazyStudy/releases/download/v2.6.2/Lazyxue_2.6.2_44p.apk)下载
> 我一直在用，不应该啊

可以了,下的分支releases里的不行,你这个链接又可以....
