### ISSUE TITLE
懒人2.7.0   的挑战答题   正确率  超低   

### ISSUE THREAD

**Issue by 1761630764** [lolisaikou/LazyStudy#70]

**Comment by hanguowei98** [comment]
是的，自从网络题库出问题后，就没有更新了！

**Comment by Muyanglaw** [comment]
评论里边有个朋友发的题库挺好的，推荐下载。正确率很高

**Comment by xiezm** [comment]
> 评论里边有个朋友发的题库挺好的，推荐下载。正确率很高
提供一下地址

**Comment by haoguowei98** [comment]
> > 评论里边有个朋友发的题库挺好的，推荐下载。正确率很高
> > 提供一下地址

这个题库前面我分享出来的      https://www.lanzoui.com/i0dD8hagc0f

**Comment by hanguowei98** [comment]
> 评论里边有个朋友发的题库挺好的，推荐下载。正确率很高
 > 提供一下地址

就这个题库，前面我分享出来的。https://www.lanzoui.com/i0dD8hagc0f
