### ISSUE TITLE
百万血书   求更新挑战答题

### ISSUE THREAD

**Issue by 1761630764** [lolisaikou/LazyStudy#73]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by hanguowei98** [comment]
用这个题库，前面我分享出来的，正确率比较高。https://www.lanzoui.com/i0dD8hagc0f
