### ISSUE TITLE
新版本挑战答题怎么样      

### ISSUE THREAD

**Issue by 1761630764** [lolisaikou/LazyStudy#74]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by nmcq** [comment]
题库还是不太行

**Comment by hanguowei98** [comment]
> 题库还是不太行

用这个题库，前面我分享出来的，正确率比较高。https://www.lanzoui.com/i0dD8hagc0f

**Comment by nmcq** [comment]
> > 题库还是不太行
> 
> 用这个题库，前面我分享出来的，正确率比较高。https://www.lanzoui.com/i0dD8hagc0f

试了下。可以的，哪儿找的
