### ISSUE TITLE
点开始浏览   跳到积分获取一下状态，自己不会浏览，不知道什么情况

### ISSUE THREAD

**Issue by nmcq** [lolisaikou/LazyStudy#75]
你的手机型号：华为 P30 PRO

你的安卓版本：7.0   以上

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：点开始浏览   跳到积分获取一下状态，自己不会浏览，不知道什么情况

**Comment by nmcq** [comment]
而且点停止以后会关闭无障碍

**Comment by nmcq** [comment]
视听时长结束了。然后不动了

**Comment by adamnb1** [comment]
我，小米CC9pro  ，安卓10，广播，获取积分，然后就不动了。

**Comment by nmcq** [comment]
> 我，小米CC9pro  ，安卓10，广播，获取积分，然后就不动了。

问题解决了。 找xxqg_v3.1.3.js里  找到这段，function articleStudy(x) {
    while (!desc("工作").exists());//等待加载出主页
    console.log("进入学习函数");
    var listView = className("ListView");//获取文章ListView控件用于翻页
    console.log("获取list了");
    if (x == 0) {
        console.log("进入if函数");
       desc("工作").click();//点击主页正下方的"学习"按钮       **这里啊，这个引号里的“学习“改成”工作“**
        delay(2);
        console.log(aCatlog);
        delay(2);
        click("推荐");

    }

**Comment by 1761630764** [comment]
function articleStudy(x) {
    while (!desc("工作").exists());//等待加载出主页
    var listView = className("ListView");//获取文章ListView控件用于翻页
    if (x == 0) {
        desc("工作").click();//点击主页正下方的"学习"按钮
        delay(2);
        click(aCatlog);
    }
    delay(2);
    var zt_flag = false;//判断进入专题界面标志
    var fail = 0;//点击失败次数
    var date_string = getTodayDateString();//获取当天日期字符串
    for (var i = 0, t = 0; i < aCount;) {
        try {
            if ((id("general_card_title_id").findOnce(t).parent().parent().click() || id("general_card_title_id").findOnce(t).parent().parent().parent().click()) == true) {
                delay(5);
                // // delay(10); //等待加载出文章页面，后面判断是否进入了视频文章播放要用到
                //获取当前正在阅读的文章标题
                let n = 0;
                while (!textContains("欢迎发表你的观点").exists()) {//如果没有找到评论框则认为没有进入文章界面，一直等待
                    delay(2);
                    console.warn("正在等待加载文章界面...");
                    if (n > 3) {//等待超过3秒则认为进入了专题界面，退出进下一篇文章
                        console.warn("没找到评论框!该界面非文章界面!");
                        zt_flag = true;
                        break;
                    }
                    n++;
                }
                if (text("展开").exists()) {//如果存在“展开”则认为进入了文章栏中的视频界面需退出
                    console.warn("进入了视频界面，退出并进入下一篇文章!");
                    t++;
                    back();
                    if (rTime != 0) {
                        while (!desc("工作").exists());
                        console.info("因为广播被打断，重新收听广播...");
                        delay(0.5);
                        listenToRadio();//听电台广播
                        while (!desc("工作").exists());
                        desc("学习").click();
                    }
                    delay(2);
                    continue;
                }
                if (zt_flag == true) {//进入专题页标志
                    console.warn("进入了专题界面，即将退出并进下一篇文章!");
                    t++;
                    back();
                    delay(2);
                    zt_flag = false;
                    continue;



代码不太一样，出现的情况一样    帮忙看一下

**Comment by zhuxuedefeng** [comment]
> while (!desc("工作").exists());
> desc("学习").click();
> }

该代码中"学习"修改为"工作"。不过，我建议修改为基于id判断点击。学习按钮id为 id("home_bottom_tab_button_work")用法如下：
if (id("home_bottom_tab_button_work").exists()) {
 id("home_bottom_tab_button_work").findOne().click(); }
while (!id("home_bottom_tab_button_work").exists()) {
 id("home_bottom_tab_button_work").findOne().click(); }

**Comment by zhuxuedefeng** [comment]
20201001 学习按钮文字属性由"学习"改为 "工作"，所有点击学习按钮加载主页均需同步修改
