### ISSUE TITLE
正确率较高的db新题库

### ISSUE THREAD

**Issue by hanguowei98** [lolisaikou/LazyStudy#77]
题库链接：https://www.lanzoui.com/ii3Ryhai3ha

**Comment by adamnb1** [comment]
> 题库链接：https://www.lanzoui.com/ii3Ryhai3ha

这个如何使用？详细说一下如何

**Comment by hanguowei98** [comment]
> > 题库链接：https://www.lanzoui.com/ii3Ryhai3ha
> 
> 这个如何使用？详细说一下如何

这个只能用在使用源码的用户！

**Comment by adamnb1** [comment]
> > > 题库链接：https://www.lanzoui.com/ii3Ryhai3ha
> > 
> > 
> > 这个如何使用？详细说一下如何
> 
> 这个只能用在使用源码的用户！

明白了
我原来用过原码

**Comment by nickyleu** [comment]
感谢分享

**Comment by keep-an** [comment]
有几十个空答案   题目有但是答案是空的
