### ISSUE TITLE
最新版2.7.1运行BUG

### ISSUE THREAD

**Issue by DoveBoy** [lolisaikou/LazyStudy#79]
你的手机型号：OnePlus 5T

你的安卓版本：10

错误的截图：
![Screenshot_20201013-080030](https://user-images.githubusercontent.com/19201447/95800836-01ce8a80-0d2b-11eb-950c-c73af3a38b60.jpg)

错误描述：使用源代码执行的，强国最新版本2.17.1，执行脚本的开始浏览后，只会自动跳转到听电台节目，但是其他的任何任务都不会执行（浏览文章，观看视频等等）。另外一个问题就是更新挑战题库每次都是提示更新7878，从来没有变过，是不是现在挑战题库再也不能更新题库了？请大佬修复一下吧！

**Comment by 1761630764** [comment]
一模一样，就到打开电台后，返回主界面就没反应了，一加5

**Comment by zhuxuedefeng** [comment]
20201001 学习按钮文字属性由"学习"改为 "工作"，以下所有点击学习按钮加载主页均同步修改@Mr-zhao98 @DoveBoy 
建议基于id点击判断，
           if (id("home_bottom_tab_button_work").exists()) {
            id("home_bottom_tab_button_work").findOne().click();}
            while (!id("home_bottom_tab_button_work").exists()) {
            id("home_bottom_tab_button_work").findOne().click();}

**Comment by zouyingfeng** [comment]
你这个版本在哪里下载啊？
