### ISSUE TITLE
更新题库提示 更新undefined道题！

### ISSUE THREAD

**Issue by jw8013** [lolisaikou/LazyStudy#8]
你的手机型号：Xiaomi RedmiK20 Pro Premium Edition

你的安卓版本：Android10

错误的截图：![](https://ftp.bmp.ovh/imgs/2020/07/e325bf9ddd9d50fb.jpg)

错误描述：题库更新完提示 更新undefined道题！

**Comment by lolisaikou** [comment]
这个我自己用的时候也遇到了，其实是能正常入库的，不影响使用
