### ISSUE TITLE
关于题库更新和新的争上游答题与双人对战

### ISSUE THREAD

**Issue by tq036my** [lolisaikou/LazyStudy#80]
1、原先题库地址变化，http://49.235.90.76:5000失效后变成https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json，能否设置指定题库地址，防止失联，另外也可以自己根据需要手工加减。
2、新上的争上游答题与双人对战和挑战答题题库有重合，能否增加答题功能。

**Comment by nmcq** [comment]
> https://cdn.jsdelivr.net/gh/lolisaikou/tiku-autoupdate/questions.json，能否设置指定题库地址，防止失联，另外也可以自己根据需要手工加减。

有争上游功能了?
