### ISSUE TITLE
哪位大神扫盲一下如何导入AutoJs中吧，哪个是主程序。谢谢

### ISSUE THREAD

**Issue by adamnb1** [lolisaikou/LazyStudy#83]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by 1761630764** [comment]
main   其他不知道

**Comment by chongyadong** [comment]
直接把解压出来的文件夹复制到根目录/脚本文件夹下，然后到js运行就可以了

**Comment by adamnb1** [comment]
> 直接把解压出来的文件夹复制到根目录/脚本文件夹下，然后到js运行就可以了
感谢。这样操作后，导入项目，却把所有的文件都列在项目下面。不过左右能用了。谢谢

**Comment by 1761630764** [comment]
> 直接把解压出来的文件夹复制到根目录/脚本文件夹下，然后到js运行就可以了

导入以后运行main.js   打开电台后   返回主界面就没反应了  不自动学习文章视频了   是哪的问题

**Comment by chongyadong** [comment]
> > 直接把解压出来的文件夹复制到根目录/脚本文件夹下，然后到js运行就可以了
> 
> 导入以后运行main.js 打开电台后 返回主界面就没反应了 不自动学习文章视频了 是哪的问题

链接: https://pan.baidu.com/s/15Q3GJL6ZR88aMT0sxHuptg 提取码: c7ee 那你可以试试我自己修改的这个
