### ISSUE TITLE
无法进行文章预览，识别不出已经在主页T﹏T

### ISSUE THREAD

**Issue by qq251347273** [lolisaikou/LazyStudy#84]
你的手机型号：
mate20 
你的安卓版本：
EMUI9.0
错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by zhuxuedefeng** [comment]
建议用Auto.JS分析一下学习按钮所包含的文字，看是"学习"还是"工作"，然后对应修改代码。最好是改成基于id点击。
