### ISSUE TITLE
auto.js运行的，自动运行到打开本地电台，就不会停在那了

### ISSUE THREAD

**Issue by 1761630764** [lolisaikou/LazyStudy#86]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by 1761630764** [comment]
点击开始浏览后   识别完  积分   返回主界面   就没反应了

**Comment by zhuxuedefeng** [comment]
查看积分获取的内容是否正常，部分手机返回Null会不运行。可以修改为不识别积分，预置数目执行。不过这样不能进行基于积分循环判断，完毕后需要手动检查。

**Comment by lolisaikou** [comment]
因为这个是用autojs pro8.0编写的，所以可能会不兼容autojs 4.0版本
