### ISSUE TITLE
老哥，可以弄个tg电报群反馈交流吗

### ISSUE THREAD

**Issue by shajia1992** [lolisaikou/LazyStudy#87]
老哥，可以弄个tg电报群反馈交流吗

**Comment by adamnb1** [comment]
严重支持，哪位大仙搞个电报群吧。

**Comment by zhuxuedefeng** [comment]
https://gitter.im/AutoJSQiangGuo/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link
不知道我创建的参数对不对。电脑端QG项目TechXueXi在用。可GitHub授权登录。
