### ISSUE TITLE
脚本运行是不是没有一键42分的压缩包

### ISSUE THREAD

**Issue by 1761630764** [lolisaikou/LazyStudy#88]
@你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）
@lolisaikou 
错误描述：

**Comment by hanguowei98** [comment]
有啊！https://github.com/lolisaikou/LazyStudy/archive/onekey.zip

**Comment by 1761630764** [comment]
我怎么没找到，，，你在哪找到的

**Comment by 1761630764** [comment]
而且下载不下来

**Comment by hanguowei98** [comment]
> 而且下载不下来

可以下载的，就是慢些！

**Comment by Ivan-cn** [comment]
点“master”右边的向下箭头，选"onekey"就行了
