### ISSUE TITLE
同学们，请简单描述下做学习强国的顺序

### ISSUE THREAD

**Issue by zhuxuedefeng** [lolisaikou/LazyStudy#89]
AI要模拟人，离不开大数据。

xxqg_help 3.1.3 ui修改版 AI强国 UI逻辑:
文章 12篇30秒（前2篇文章分享点赞评论），视频 6个60秒，本地频道，挑战答题 1轮*5题，每日答题（至领取奖励已达今日上限）
之后循环检查 文章个数时长积分、视频个数积分，本地，挑战，每日答题 积分，不足则循环执行。
以上足够之后，检查分享评论积分，不足则学习2篇文章执行分享点赞评论；检查视频时长，不足则收听广播补时长（广播不会自动退出，但不影响接下来执行）；检查双人对战积分，<1执行一次双人对战；检查争上游答题积分，<2执行两次争上游答题。

其中: 
文章的点击逻辑: 综合 要闻 综合，三个随机选一个，按日期点击文章，首先检查今天，今天没有，随机选前几天，再点击。再次点击失败或中途出错，换点击文本"学习强国平台"
视频点击逻辑，电视台，第一频道 学习视频 联播频道 三个随机选一个，第一频道点击央视网，学习视频点击央视新闻，联播频道点击中央广播电视总台。如果点击失败，下滑再次检索，三次点击失败，随机换上面三个频道。
评论内容，随机三句话中选一句。
文章视频评论三项使用一个随机数，这样处理简单。

**Comment by zhuxuedefeng** [comment]
AI强国脚本目前存在 电台先于文章打开，点击文章时很大概率重复打开电台收听页。故不考虑在文章之前先收听电台的流程。(做了判断退出电台收听页代码，但架不住总是重复点进)

**Comment by KB64ba** [comment]
> AI强国脚本目前存在 电台先于文章打开，点击文章时很大概率重复打开电台收听页。故不考虑在文章之前先收听电台的流程。(做了判断退出电台收听页代码，但架不住总是重复点进)

建议修改成以文章列表中的播报做为基准点，反查文章标题点击，再以是否收藏为浏览记录。这样就不容易出错。

如果要以随机阅读浏览的，建议每个项使用3个并且3个记录不在一个列表。

建议增加界面判断，能在各个界面能返回到主页，那怕退出也能重新打开APP就好，

**Comment by zhuxuedefeng** [comment]
> > AI强国脚本目前存在 电台先于文章打开，点击文章时很大概率重复打开电台收听页。故不考虑在文章之前先收听电台的流程。(做了判断退出电台收听页代码，但架不住总是重复点进)
> 
> 建议修改成以文章列表中的播报做为基准点，反查文章标题点击，再以是否收藏为浏览记录。这样就不容易出错。
> 
> 如果要以随机阅读浏览的，建议每个项使用3个并且3个记录不在一个列表。
> 
> 建议增加界面判断，能在各个界面能返回到主页，那怕退出也能重新打开APP就好，

前面chongyadong同学已提到基于播报区分文章和视频，明天测试。
界面判断，如果在每个函数里都判断有点难度，初始拉起强国app时基于经常打开的页面判断返回主页这个难度不大。
不知道autojs有没有暂停/继续执行的按钮代码，这个更实用。
最后，开本贴主要想讨论大家手动做题时的大概流程，以便模拟人工来避开可能的后台监测。功能上的建议还请在另一贴讨论。

**Comment by Ivan-cn** [comment]
//各个学习模块，除广播电台先开始听,其他各个学习模块随机顺序执行
//分为10个模块随机顺序执行
//文章和视频均加上随机数，全局变量
var aTime = 30 + random(5, 15);//每篇文章学习-30秒 30*12≈360秒=6分钟
var vTime = 15 + random(5, 15);//每个小视频学习-15秒
var rTime = 360 + random(5, 15);//广播收听6分 * 60 = 360秒

//主要函数，xx9和10会打断电台，可以考虑单独放在后面随机执行，但经过1天随机测试，好像也正常，其中start_app()和getScores()函数我简单修改了下

function xx1(){
    console.log("正在准备每日答题");
    if (myScores['每日答题'] != 5) {
        dailyQuestion();//每日答题
    }
}

function xx2(){ 
    console.log("正在准备挑战答题");
    if (myScores['挑战答题'] != 6) {
        challengeQuestion();//挑战答题
    }
}

function xx3(){
    console.log("正在准备进行订阅");
    if (myScores['订阅'] != 2) {
        sub();//订阅
    }
}

function xx4(){
    console.log("正在准备本地频道");
    if (myScores['本地频道'] != 1) {
        localChannel();//本地频道
    }
}

  
function xx5(){
    console.log("正在准备争上游答题");
	if (myScores["争上游答题"] < 2) {
        zsyQuestion();//争上游答题
    }
}

function xx6(){
    console.log("正在准备双人对战");
    if (myScores["双人对战"] < 1) {
        SRQuestion();//双人对战
    }  
}

function xx7(){
    console.log("正在准备每周答题");
    if (myScores['每周答题'] == 0) {//无分值即尝试答题
        weeklyQuestion();//每周答题
	}
}

function xx8(){
    console.log("正在准备专项答题");
    if (myScores['专项答题'] == 0) {//无分值即尝试答题
      specialQuestion();//专项答题
  }
}

function xx9(){
    console.log("正在准备视频学习");
    while (vCount != 0) {
        var x = 0;
        num = random(0, commentText.length - 1) ; //重取随机数        
        if (num==0) {
            videoStudy_bailing(vCount, vTime);//百灵视频
        } else {
            videoStudy_news();//看视频
        }
        console.info("等待5秒，然后确认视频是否已满分。");
        delay(5);
        getScores(2);
        x++;
        if (x > 2) {//尝试三次
            console.info("尝试3次未满分，暂时跳过。");
            break;
        }
        vCatlog = vCat[num] ;
        delay(1);                               
    }
}

function xx10(){
    console.log("正在准备文章学习");
	while (aCount != 0) {
        var x = 0;
        articleStudy(x);//学习文章，包含点赞、分享和评论
        console.info("等待5秒，然后确认文章是否已满分。");
        delay(5);
        getScores(1);
        x++;
        if (x > 2) {//尝试三次
            console.info("尝试3次未满分，暂时跳过。");
            break;
        }
        delay(1);
        num = random(0, commentText.length - 1) ; //重取随机数
        aCatlog = aCat[num] ;               
    }
}

function main() {	
	auto.waitFor();//等待获取无障碍辅助权限
    start_app();//启动app
    var path = files.path("list.db");
    var start = new Date().getTime();//程序开始时间

    getScores();//获取积分
	
    //听电台广播
    var needRadio =true;
    if (myScores['视听学习时长'] != 6){
        console.log("正在准备电台广播");
        listenToRadio();//听电台广播
    }else {
        var needRadio=false;//如果电台广播已完成
    }
    
    
	//原来学习文章，包含点赞、分享和评论改为随机顺序学习
    var funArr = [xx1,xx2,xx3,xx4,xx5,xx6,xx7,xx8,xx9,xx10],func;//随机学习各模块
    while(funArr.length != 0){
        func = funArr.splice(random(0,funArr.length-1),1)[0];
        start_app(1);
        func();
    }//随机学习各模块

    var end = new Date().getTime();//重新开始广播时间
    if ( needRadio ) {
        if (myScores['视听学习时长'] != 6){
            console.log("重新开始电台广播");
            listenToRadio();//听电台广播
            //var end = new Date().getTime();//重新开始广播时间
            var radio_time = (parseInt((end) / 1000));//广播已经收听的时间
            radio_timing(parseInt((end ) / 1000), rTime - radio_time);//广播剩余需收听时间
            if (rTime == 0) {//停止播放广播
                console.log("正在准备停止广播");
                stopRadio();
            }
        }
    }
    
    end = new Date().getTime();//结束时间
	console.info("您今日学习获得"+xxScores+"分");
    console.log("运行结束,共耗时" + (parseInt(end - start)) / 1000 + "秒");
    files.copy(path, "/sdcard/Download/list.db");
    console.warn("自动备份已学文章列表到/sdcard/Download!!!");
}
