### ISSUE TITLE
我有两个号，第二个号浏览文章会自动退出怎么办？

### ISSUE THREAD

**Issue by zxcvbnm3111** [lolisaikou/LazyStudy#9]
文章标题记录问题，就是如果 有两个号，那么前面 看过的在第二个号就是已浏览了就 退出这章了

**Comment by 85524365** [comment]
我也是一个手机学习两个号码，自己的和领导的。
估计很多人这样，大神，如果能自动以2个手机号码建2个文件夹，各自保存各自的学习内容，就完美了。
说的容易，做的难，仅供参考哈

**Comment by zxcvbnm3111** [comment]
很上进吖

**Comment by lolisaikou** [comment]
> 我也是一个手机学习两个号码，自己的和领导的。
> 估计很多人这样，大神，如果能自动以2个手机号码建2个文件夹，各自保存各自的学习内容，就完美了。
> 说的容易，做的难，仅供参考哈

这个怎么说呢，有两种解决方案：
一、如果你的手机支持双开的话（也有软件可以做到），双开强国，然后把启动app的代码修改一下，就可以在第二个的强国里使用了
二、你的手机支持分身的话，那就更简单了，直接把强国和我的app装在分身里就行

**Comment by lolisaikou** [comment]
# 2.6.8版本后在题库界面增加了清空文章列表的按钮，需要给第二个账号学习的话可以直接按这个按钮来清空列表。

四个解决方案
一、非常简单
淘一个旧手机（记得安卓版本要>=7.0）
二、比较麻烦（免费）
需要手机支持分身（不是应用分身，是手机分身（理论上应用分身也能用，未实践））
手机不支持分身但手机性能不错（比如华为），可以试试用[VMOS](https://www.vmos.cn/)（非广告）
在分身内部安装这个程序和强国就可以了
三、非常麻烦（免费）
第一步：[下载autojs4.0（免费版）](https://lolisaikou.lanzous.com/iIrieez5t9c)
下载后先打开一次软件，然后用系统自带的文件管理器进入根目录的”脚本“文件夹
（因为各品牌手机操作不同这里仅作演示，实在不知道如何操作可以请教别人或者百度）
![image](https://user-images.githubusercontent.com/32028165/88452316-41a27600-ce90-11ea-9141-9b0779b2bee3.png)
最后新建一个文件夹（文件名随意）
第二步：
[下载本项目代码](https://github.com/lolisaikou/LazyStudy/archive/master.zip)
[下载本项目代码（一键44分版）](https://github.com/lolisaikou/LazyStudy/archive/onekey.zip)
上面的文件二选一下载，看你喜欢用哪个版本
![image](https://user-images.githubusercontent.com/32028165/88452582-97781d80-ce92-11ea-88b8-a6469a06deeb.png)
下载后打开
![image](https://user-images.githubusercontent.com/32028165/88452593-afe83800-ce92-11ea-8ca0-e9d692e2c0a9.png)
解压到刚才你创建的文件夹
![image](https://user-images.githubusercontent.com/32028165/88452638-f50c6a00-ce92-11ea-8753-caab27b8c8a6.png)
打开autojs点击按钮运行
四、试试可以称作是本项目父亲的[ivanwhaf/xxqg-helper](https://github.com/ivanwhaf/xxqg-helper)脚本（本项目大部分代码都是从那边来的）为什么这个放在最后，就是那边脚本更新较慢，不一定适配最新版，而且有些功能这边有那边没有

**Comment by Muyanglaw** [comment]
> 文章标题记录问题，就是如果 有两个号，那么前面 看过的在第二个号就是已浏览了就 退出这章了

你在 脚本 目录下新建一个文件夹，把脚本跟数据库拷贝进去，在auto.js中点开这个新建的文件夹去运行脚本就跟那个是相互独立的了，我也是这样帮领导听课的

**Comment by 85524365** [comment]
> > 文章标题记录问题，就是如果 有两个号，那么前面 看过的在第二个号就是已浏览了就 退出这章了
> 
> 你在 脚本 目录下新建一个文件夹，把脚本跟数据库拷贝进去，在auto.js中点开这个新建的文件夹去运行脚本就跟那个是相互独立的了，我也是这样帮领导听课的

妙不可言，感谢分享

**Comment by Ivan-cn** [comment]
把UI和xxqg_v3.1.3中的list.db改名list2.db之类，然后编译为apk，就可以有2个apk了，但启动前还需要启动学习强国退出帐号和登录相应的账号，好像有点麻烦，能否支持一键化操作呢？

**Comment by lolisaikou** [comment]
下个版本会在题库页面做一个按钮，直接清空数据库

**Comment by Ivan-cn** [comment]
> 下个版本会在题库页面做一个按钮，直接清空数据库

我写了简单模块，命名为xxqg_v3.1.3(fix)，将原来的改为指定名字（如xxqg_v3.1.3(xx)），也就是先启动我的模块来退出帐号和输入指定的账号，然后再调用原来的xxqg_v3.1.3(xx)来启动，一切都那么自由。

**Comment by zxcvbnm3111** [comment]
> > 下个版本会在题库页面做一个按钮，直接清空数据库
> 
> 我写了简单模块，命名为xxqg_v3.1.3(FIX)，将原来的改为指定名字(如xqg_v3.1.3(Xx)，也就是先启动我的模块来退出帐号和输入指定的账号，然后再调用原来的xxqg_v3.1.3(Xx)来启动，一切都那么自由。

能不能看看你的源码

**Comment by Ivan-cn** [comment]
> > > 下个版本会在题库页面做一个按钮，直接清空数据库
> > 
> > 
> > 我写了简单模块，命名为xxqg_v3.1.3(FIX)，将原来的改为指定名字(如xqg_v3.1.3(Xx)，也就是先启动我的模块来退出帐号和输入指定的账号，然后再调用原来的xxqg_v3.1.3(Xx)来启动，一切都那么自由。
> 
> 能不能看看你的源码

/**
 * 说明：
 *
 * 		1.将原"xxqg_v3.1.3(fix).js"改名为"!xxqg_v3.1.3(fix).js"(不含引号，下同）
 * 		2.将此文件改名为"xxqg_v3.1.3(fix).js"
 * 		3.设置你的强国账号和密码，需要在强国APP上登录过（即设备已授权登录）
 *		4.建议将"UI.js"和"!xxqg_v3.1.3(fix).js"里面的"list.db"内容修改，如加上后缀"listx.db"（默认的自动备份为Download\list.db）
 *		5.复制到auto.js的项目目录，运行或编译即可享用
 * 	
 * 		作者：Ivan
 *		日期：2020.8.18 
 */

 //账号
var user="12345678910"
//密码
var passward="12345678"
//登录帐号
function input_xxid(){
    id("et_phone_input").findOne().setText(user);
    id("et_pwd_login").findOne().setText(passward);
    id("btn_next").findOne().click();
    sleep(2000);
    console.log(user+"帐号已登录！");
    toast(user+"帐号已登录！");
    sleep(1000);
}
//退出原帐号
function exit_xxid(){
    //id("comm_head_xuexi_mine").findOne().click();
    text("我的").findOne().click()
    sleep(2000);
    id("my_setting").findOne().click();
    sleep(2000);
    //退出登录
    if (text("退出登录").exists()) {
    	click("退出登录"); 
    }
    //sleep(800);
    if (text("确认").exists()) {
    	click("确认"); 
    }
    console.log("正在退出原帐号…");
    sleep(1000);
}
//启动学习强国
function start_app() {
    console.setPosition(0, device.height / 2);//部分华为手机console有bug请注释本行
    console.show();//部分华为手机console有bug请注释本行
    console.log("正在启动app...");
    if (!launchApp("学习强国"))//启动学习强国app
    {
        console.error("找不到学习强国App!");
        return;
    }
    while (!desc("学习").exists())  {
        console.log("正在等待加载出主页");
        sleep(2000);
        //未登陆？
        if (!desc("输入密码").exists()) {
            if(id("et_phone_input").exists()){
            input_xxid();
            return;
            }
        }
    }
    sleep(1000);
    exit_xxid();
    input_xxid();
    sleep(1000);
}
//以线程形式运行
function main(){
    start_app();
    back();
    //启动答题线程
    var ss = "./!xxqg_v3.1.3(fix).js";
    let begin = require(ss);
    begin();
}
module.exports = main;

**Comment by Ivan-cn** [comment]
> > > 下个版本会在题库页面做一个按钮，直接清空数据库
> > 
> > 
> > 我写了简单模块，命名为xxqg_v3.1.3(FIX)，将原来的改为指定名字(如xqg_v3.1.3(Xx)，也就是先启动我的模块来退出帐号和输入指定的账号，然后再调用原来的xxqg_v3.1.3(Xx)来启动，一切都那么自由。
> 
> 能不能看看你的源码

改写了代码，自动切换账号学习，学习完毕后推送到微信提醒，感觉还可以。
