### ISSUE TITLE
对战  ，   如果不小心点到对战  ， 提示    没找那两项的开始界面  ，  然后悬浮窗会自动退出    ，  建议点错了给提示，  别让悬浮窗关闭

### ISSUE THREAD

**Issue by 1761630764** [lolisaikou/LazyStudy#92]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by lolisaikou** [comment]
已更新
