### ISSUE TITLE
在tg上发现了这个APP，试了下对战答题速度特别快

### ISSUE THREAD

**Issue by 1celife** [lolisaikou/LazyStudy#94]
[时光脚本_6.15_共存防报毒.zip](https://github.com/lolisaikou/LazyStudy/files/5419561/_6.15_.zip)
http://app.sg89.cn/app/21.html

**Comment by KB64ba** [comment]
他这个好像是用在线题库

**Comment by Ivan-cn** [comment]
可惜源代码加密了，但也是在xxqg的基础上改的

**Comment by zxcvbnm3111** [comment]
> [时光脚本_6.15_共存防报毒.zip](https://github.com/lolisaikou/LazyStudy/files/5419561/_6.15_.zip)
> http://app.sg89.cn/app/21.html

tg群分享一下

**Comment by shajia1992** [comment]
哥，求tg群，万分感谢

**Comment by 1celife** [comment]
> > [时光脚本_6.15_共存防报毒.zip](https://github.com/lolisaikou/LazyStudy/files/5419561/_6.15_.zip)
> > http://app.sg89.cn/app/21.html
> 
> tg群分享一下

https://t.me/fuckxuexi
这个群之前随便加的，没怎么看过。软件里可以加作者QQ群

**Comment by zhuxuedefeng** [comment]
不开放源代码，不好玩

**Comment by Ivan-cn** [comment]
> 不开放源代码，不好玩

就是啊，明明是用了xxqg-helper的代码。。。
不过我已偷偷查到他的在线题库搜题的方法，但还没试验，对方也没有授权，等试验通过了再分享吧

**Comment by Muyanglaw** [comment]
这个作者用心了啊，功能很全，而且免费。

**Comment by Ivan-cn** [comment]
> 这个作者用心了啊，功能很全，而且免费。

服务器端验证了，数据库搜不了了。

**Comment by aweder** [comment]
华为荣耀30提示这个APP已经感染病毒，而且要开截屏权限和各种各样的权限，不太敢使用

**Comment by zhuxuedefeng** [comment]
> 华为荣耀30提示这个APP已经感染病毒，而且要开截屏权限和各种各样的权限，不太敢使用

不开源，AutoJS非专业版打包的本来就容易误报。开源，有疑虑的可以自己检查代码自己打包。

**Comment by gmfusheng** [comment]
> > 这个作者用心了啊，功能很全，而且免费。
> 
> 服务器端验证了，数据库搜不了了。

这个作者已经更新了，需要注册，注册要注册码...
