### ISSUE TITLE
求一个每天都定时启动指定app的脚步

### ISSUE THREAD

**Issue by 1761630764** [lolisaikou/LazyStudy#95]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by 85524365** [comment]
同求，嘿嘿

**Comment by Muyanglaw** [comment]
你手机不亮屏开机，它怎么帮你自动运行？不现实

**Comment by Wangzifu98** [comment]
xp框架可以定时解锁手机运行

**Comment by Ivan-cn** [comment]
//唤醒并解锁(用于定时任务)
while (!device.isScreenOn()) {
    sleep(1500);
    device.wakeUpIfNeeded();
    device.wakeUp();//唤醒    
    //console.log(currentPackage());
    if (device.device == "HLTE202N") {
    	//海信A5，数字解锁，可参考修改，含下面的上滑解锁
        desc(1).findOne().click();
        desc(2).findOne().click();
        desc(3).findOne().click();
        desc(4).findOne().click();
        desc(5).findOne().click();
        desc(6).findOne().click();
    }
    if (device.device == "markw"){
    	//红米4高配版，魔趣，上滑解锁
        swipe(device.width/2, device.height-100, device.width/2, device.height/3, 300);
    }
	//解锁屏幕成功与否？
	sleep(1500);
    if (currentPackage() != "com.android.systemui") {
        DLog = detailLog(DLog, "屏幕解锁成功");
    }else{       
        DLog = detailLog(DLog, "## 屏幕解锁不成功，请检查 ##");
        //微信推送失败情况       
        var nowtime = new java.text.SimpleDateFormat('HH:mm:ss').format(new Date());
        var title=nowtime+" 自动启动懒人学习失败";
        var content=DLog;
        var wxsend=pushwx(title,content);
        //关闭悬浮窗
        console.clear();
        console.hide();
        //退出
        exit();
    } 
}

上为唤醒并解锁的主要代码，有密码解锁和上滑解锁的示例，具体可找我fork的版本，支持唤醒和多用户切换
