### ISSUE TITLE
还不更新吗 计划都提出好久了

### ISSUE THREAD

**Issue by keep-an** [lolisaikou/LazyStudy#96]
你的手机型号：

你的安卓版本：

错误的截图：
（可以到懒人学习界面，点击返回键查看日志，最好把红色的部分截下，图片可以上传到这里：https://imgurl.org/ ，然后把图片链接贴在这里）

错误描述：

**Comment by zhuxuedefeng** [comment]
做这个都是业余凭爱好做，又不是盈利商业程序。有时间了就完善一下。有问题了弃坑都有可能～～～～～

**Comment by kridlo** [comment]
去看one-key版源码嘛，更新了的

**Comment by jsjrj01** [comment]
> 去看one-key版源码嘛，更新了的

老铁，one-key我看也没更新啊（可能我是新手的原因），Ivan-cn 的one-key有更新，但是要安装autojs，并且他那个没有每日和专项。
另，是否有推荐的autojs资料？
