### ISSUE TITLE
无法运行，点打开悬浮窗就跳转无障碍

### ISSUE THREAD

**Issue by enoang** [lolisaikou/LazyStudy#98]

**Comment by henrycoding** [comment]
无障碍给权限啊

**Comment by enoang** [comment]
已经给过无障碍权限了呀

**Comment by zhuxuedefeng** [comment]
需要先给权限，再开程序。虽然已经使用了auto.waitfor申请权限，但很奇怪，程序自动申请权限返回后会莫名卡死。另外，如果被强杀进程，强行退出，还是会关闭无障碍权限。

**Comment by enoang** [comment]
> 需要先给权限，再开程序。虽然已经使用了auto.waitfor申请权限，但很奇怪，程序自动申请权限返回后会莫名卡死。另外，如果被强杀进程，强行退出，还是会关闭无障碍权限。

重新试过先给权限了，但还是会跳转无障碍，难道是因为我安装了auto.js的原因？不懂了

**Comment by zhuxuedefeng** [comment]
手机重启，我是autojs跑代码，偶尔跑飞报错autojs丢失无障碍权限有时候退出重新赋权即可，有时候需要重启赋权才行。这个据说和autojs版本有关，pro版更稳定。我是基于autojs免费版4.1.1做的，据说稳定性差点。

**Comment by enoang** [comment]
> 手机重启，我是autojs跑代码，偶尔跑飞报错autojs丢失无障碍权限有时候退出重新赋权即可，有时候需要重启赋权才行。这个据说和autojs版本有关，pro版更稳定。我是基于autojs免费版4.1.1做的，据说稳定性差点。

重启试过了，还是不行，我先靠https://github.com/lolisaikou/LazyStudy/issues/85这位老哥的顶一段吧

**Comment by KB64ba** [comment]
强行结束autojs， 退出界面，重新去无障碍先关闭在开启，保险的就重启手机。 有时卡死auto都是这么搞的。除非特殊才重启。

注意你的代码有没有重复检查无障碍

**Comment by enoang** [comment]
> 强行结束autojs， 退出界面，重新去无障碍先关闭在开启，保险的就重启手机。 有时卡死auto都是这么搞的。除非特殊才重启。
> 
> 注意你的代码有没有重复检查无障碍

感谢，我再试试
