### ISSUE TITLE
//挑战答题引入Ivan-cn的处理方式，将随机点击的正确答案写入题库

### ISSUE THREAD

**Issue by uhappylearning** [lolisaikou/LazyStudy#99]
//挑战答题引入Ivan-cn的处理方式，将随机点击的正确答案写入题库
/**
 * @description: 挑战答题循环
 * @param: conNum 连续答对的次数
 * @return: null
 */
function challengeQuestionLoop(conNum) {
    let ClickAnswer;//定义已点击答案
    if (conNum >= qCount)//答题次数足够退出，每轮qCount=5+随机1-3次
    {
        let listArray = className("ListView").findOnce().children();//题目选项列表
        let i = random(0, listArray.length - 1);
        console.log("本轮次数足够，随机点击答案");
        var question = className("ListView").findOnce().parent().child(0).text();
        console.log((conNum + 1).toString() + ".题目：" + question);
        delay(random(0.5, 1));//随机延时0.5-1秒
        listArray[i].child(0).click();//随意点击一个答案
        ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案
        console.log("随机点击:"+ClickAnswer);
        //如果随机点击答案正确，则更新到本地题库tiku表
       delay(0.5);//等待0.5秒，是否出现X
       if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" +
            "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists() || text("再来一局").exists())//遇到❌号，则答错了,不再通过结束本局字样判断
        { console.log("更新本地题库答案...");
          checkAndUpdate(question, answer, ClickAnswer);
        }
        console.log("---------------------------");
        return;
    }
    if (className("ListView").exists()) {
        var question = className("ListView").findOnce().parent().child(0).text();
        console.log((conNum + 1).toString() + ".题目：" + question);
    }
    else {
        console.error("提取题目失败!");
        let listArray = className("ListView").findOnce().children();//题目选项列表
        let i = random(0, listArray.length - 1);
        console.log("随机点击");
        delay(random(0.5, 1));//随机延时0.5-1秒
        listArray[i].child(0).click();//随意点击一个答案
        return;
    }
    var chutiIndex = question.lastIndexOf("出题单位");
    if (chutiIndex != -1) {
        question = question.substring(0, chutiIndex - 2);
    }
    question = question.replace(/\s/g, "");
    var options = [];//选项列表
    if (className("ListView").exists()) {
        className("ListView").findOne().children().forEach(child => {
            var answer_q = child.child(0).child(1).text();
            options.push(answer_q);
        });
    } else {
        console.error("答案获取失败!");
        return;
    }
    var answer = getAnswer(question, 'tiku');
    if (answer.length == 0) {//tiku表中没有则到tikuNet表中搜索答案
        answer = getAnswer(question, 'tikuNet');
    }
    console.info("答案：" + answer);
    if (/^[a-zA-Z]{1}$/.test(answer)) {//如果为ABCD形式
        var indexAnsTiku = indexFromChar(answer.toUpperCase());
        answer = options[indexAnsTiku];
        toastLog("answer from char=" + answer);
    }
    let hasClicked = false;
    let listArray = className("ListView").findOnce().children();//题目选项列表
    if (answer == "")//如果没找到答案
    {
        let i = random(0, listArray.length - 1);
        console.error("没有找到答案，随机点击");
        delay(random(0.5, 1));//随机延时0.5-1秒
        listArray[i].child(0).click();//随意点击一个答案
        ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案
        hasClicked = true;
        console.log("随机点击:"+ClickAnswer);//如果随机点击答案正确，则更新到本地题库tiku表
       delay(0.5);//等待0.5秒，是否出现X
       if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" +
            "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists() || text("再来一局").exists())//遇到❌号，则答错了,不再通过结束本局字样判断
        { console.log("更新本地题库答案...");
          checkAndUpdate(question, answer, ClickAnswer);
        }
        console.log("---------------------------");
    }
    else//如果找到了答案
    {
        listArray.forEach(item => {
            var listDescStr = item.child(0).child(1).text();
            if (listDescStr == answer) {
                delay(random(0.5, 1));//随机延时0.5-1秒
                item.child(0).click();//点击答案
                hasClicked = true;
                console.log("---------------------------");
            }
        });
    }
    if (!hasClicked)//如果没有点击成功
    {//因导致不能成功点击问题较多，故该部分不更新题库，大部分问题是题库题目适配为填空题或多选题或错误选项
        console.error("未能成功点击，随机点击");
        let i = random(0, listArray.length - 1);
        delay(random(0.5, 1));//随机延时0.5-1秒
        listArray[i].child(0).click();//随意点击一个答案
       console.log("随机点击:"+ClickAnswer);
       console.log("---------------------------");
    }
}

_Originally posted by @zhuxuedefeng in https://github.com/lolisaikou/LazyStudy/issues/85#issuecomment-717730797_

**Comment by Ivan-cn** [comment]
我改了部分代码，将点击失败和随机点击合并在一起，localTiku为全局变量，如果为true才更新。
主要代码：

    let hasClicked = false;
    let listArray = className("ListView").findOnce().children();//题目选项列表
                          
    console.info("答案：" + answer);
    //如果找到答案
    
    if (answer.length != 0)//如果到答案
    {
        var clickAns = "";
        listArray.forEach(item => {
            var listDescStr = item.child(0).child(1).text();
            if (listDescStr == answer) {
                clickAns = answer;
                //显示 对号
                var b = item.child(0).bounds();
                var tipsWindow = drawfloaty(b.left, b.top);
                //随机时长点击
                delay(0.3);
                //点击
                item.child(0).click();
                hasClicked = true;
                delay(0.3);
                //消失 对号
                tipsWindow.close();
            }
        });
    }
    if (!hasClicked || answer.length == 0){//如果没有点击成功，或找不到题目
        if (!hasClicked){
            console.error("未能成功点击，随机点击");
        }
        if (answer.length == 0) {
            console.error("未找到答案，随机点击");
        }            
        delay(0.3);
        let i = random(0, listArray.length - 1);
        listArray[i].child(0).click();//随意点击一个答案
		ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案
        console.log("随机点击:"+ClickAnswer);
        console.log("------------------------");
        //随机点击答案正确，更新到本地题库tiku表
        delay(0.5);//等待0.5秒，是否出现X
        if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" + 
            "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists()) {        
                if (localTiku)   {
                    console.log("更新本地题库答案...");
                    var ansTiku = getAnswer(question, 'tiku');    
                    if (ansTiku == "") { //题库为空则插入正确答案                
                        var sql = "INSERT INTO tiku VALUES ('" + question + "','" + ClickAnswer + "','')";
                    } else { //更新题库答案
                        var sql = "UPDATE tiku SET answer='" + ClickAnswer + "' WHERE question LIKE '" + question + "'";
                    }
                    insertOrUpdate(sql);         
                    delay(0.5);
                }               
        }           
    }   		
}

**Comment by zhangop9** [comment]
> 我改了部分代码，将点击失败和随机点击合并在一起，localTiku为全局变量，如果为true才更新。
> 主要代码：
> 
> ```
> let hasClicked = false;
> let listArray = className("ListView").findOnce().children();//题目选项列表
>                       
> console.info("答案：" + answer);
> //如果找到答案
> 
> if (answer.length != 0)//如果到答案
> {
>     var clickAns = "";
>     listArray.forEach(item => {
>         var listDescStr = item.child(0).child(1).text();
>         if (listDescStr == answer) {
>             clickAns = answer;
>             //显示 对号
>             var b = item.child(0).bounds();
>             var tipsWindow = drawfloaty(b.left, b.top);
>             //随机时长点击
>             delay(0.3);
>             //点击
>             item.child(0).click();
>             hasClicked = true;
>             delay(0.3);
>             //消失 对号
>             tipsWindow.close();
>         }
>     });
> }
> if (!hasClicked || answer.length == 0){//如果没有点击成功，或找不到题目
>     if (!hasClicked){
>         console.error("未能成功点击，随机点击");
>     }
>     if (answer.length == 0) {
>         console.error("未找到答案，随机点击");
>     }            
>     delay(0.3);
>     let i = random(0, listArray.length - 1);
>     listArray[i].child(0).click();//随意点击一个答案
> 	ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案
>     console.log("随机点击:"+ClickAnswer);
>     console.log("------------------------");
>     //随机点击答案正确，更新到本地题库tiku表
>     delay(0.5);//等待0.5秒，是否出现X
>     if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" + 
>         "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists()) {        
>             if (localTiku)   {
>                 console.log("更新本地题库答案...");
>                 var ansTiku = getAnswer(question, 'tiku');    
>                 if (ansTiku == "") { //题库为空则插入正确答案                
>                     var sql = "INSERT INTO tiku VALUES ('" + question + "','" + ClickAnswer + "','')";
>                 } else { //更新题库答案
>                     var sql = "UPDATE tiku SET answer='" + ClickAnswer + "' WHERE question LIKE '" + question + "'";
>                 }
>                 insertOrUpdate(sql);         
>                 delay(0.5);
>             }               
>     }           
> }   		
> ```
> 
> }

能做一个没有微信推送的版本吗？

**Comment by Ivan-cn** [comment]
> > 我改了部分代码，将点击失败和随机点击合并在一起，localTiku为全局变量，如果为true才更新。
> > 主要代码：
> > ```
> > let hasClicked = false;
> > let listArray = className("ListView").findOnce().children();//题目选项列表
> >                       
> > console.info("答案：" + answer);
> > //如果找到答案
> > 
> > if (answer.length != 0)//如果到答案
> > {
> >     var clickAns = "";
> >     listArray.forEach(item => {
> >         var listDescStr = item.child(0).child(1).text();
> >         if (listDescStr == answer) {
> >             clickAns = answer;
> >             //显示 对号
> >             var b = item.child(0).bounds();
> >             var tipsWindow = drawfloaty(b.left, b.top);
> >             //随机时长点击
> >             delay(0.3);
> >             //点击
> >             item.child(0).click();
> >             hasClicked = true;
> >             delay(0.3);
> >             //消失 对号
> >             tipsWindow.close();
> >         }
> >     });
> > }
> > if (!hasClicked || answer.length == 0){//如果没有点击成功，或找不到题目
> >     if (!hasClicked){
> >         console.error("未能成功点击，随机点击");
> >     }
> >     if (answer.length == 0) {
> >         console.error("未找到答案，随机点击");
> >     }            
> >     delay(0.3);
> >     let i = random(0, listArray.length - 1);
> >     listArray[i].child(0).click();//随意点击一个答案
> > 	ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案
> >     console.log("随机点击:"+ClickAnswer);
> >     console.log("------------------------");
> >     //随机点击答案正确，更新到本地题库tiku表
> >     delay(0.5);//等待0.5秒，是否出现X
> >     if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" + 
> >         "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists()) {        
> >             if (localTiku)   {
> >                 console.log("更新本地题库答案...");
> >                 var ansTiku = getAnswer(question, 'tiku');    
> >                 if (ansTiku == "") { //题库为空则插入正确答案                
> >                     var sql = "INSERT INTO tiku VALUES ('" + question + "','" + ClickAnswer + "','')";
> >                 } else { //更新题库答案
> >                     var sql = "UPDATE tiku SET answer='" + ClickAnswer + "' WHERE question LIKE '" + question + "'";
> >                 }
> >                 insertOrUpdate(sql);         
> >                 delay(0.5);
> >             }               
> >     }           
> > }   		
> > ```
> > 
> > 
> > }
> 
> 能做一个没有微信推送的版本吗？

那我在配置文件加个是否推送的开关就行，目前还在完善文章和视频阅读的环节，改写部分代码，阅读成功才记录到list.db，不成功退出再换一个（百灵除外）。

**Comment by zhangop9** [comment]
改好记的发我一份



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ivan-cn"<notifications@github.com&gt;; 
发送时间: 2020年10月30日(星期五) 上午10:23
收件人: "lolisaikou/LazyStudy"<LazyStudy@noreply.github.com&gt;; 
抄送: "55142484"<zhangop9@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lolisaikou/LazyStudy] //挑战答题引入Ivan-cn的处理方式，将随机点击的正确答案写入题库 (#99)





   
我改了部分代码，将点击失败和随机点击合并在一起，localTiku为全局变量，如果为true才更新。
 主要代码：
 let hasClicked = false; let listArray = className("ListView").findOnce().children();//题目选项列表                        console.info("答案：" + answer); //如果找到答案 if (answer.length != 0)//如果到答案 {     var clickAns = "";     listArray.forEach(item =&gt; {         var listDescStr = item.child(0).child(1).text();         if (listDescStr == answer) {             clickAns = answer;             //显示 对号             var b = item.child(0).bounds();             var tipsWindow = drawfloaty(b.left, b.top);             //随机时长点击             delay(0.3);             //点击             item.child(0).click();             hasClicked = true;             delay(0.3);             //消失 对号             tipsWindow.close();         }     }); } if (!hasClicked || answer.length == 0){//如果没有点击成功，或找不到题目     if (!hasClicked){         console.error("未能成功点击，随机点击");     }     if (answer.length == 0) {         console.error("未找到答案，随机点击");     }                 delay(0.3);     let i = random(0, listArray.length - 1);     listArray[i].child(0).click();//随意点击一个答案 	ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案     console.log("随机点击:"+ClickAnswer);     console.log("------------------------");     //随机点击答案正确，更新到本地题库tiku表     delay(0.5);//等待0.5秒，是否出现X     if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" +          "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists()) {                     if (localTiku)   {                 console.log("更新本地题库答案...");                 var ansTiku = getAnswer(question, 'tiku');                     if (ansTiku == "") { //题库为空则插入正确答案                                     var sql = "INSERT INTO tiku VALUES ('" + question + "','" + ClickAnswer + "','')";                 } else { //更新题库答案                     var sql = "UPDATE tiku SET answer='" + ClickAnswer + "' WHERE question LIKE '" + question + "'";                 }                 insertOrUpdate(sql);                          delay(0.5);             }                    }            }   		  
}
  
能做一个没有微信推送的版本吗？
  
那我在配置文件加个是否推送的开关就行，目前还在完善文章和视频阅读的环节，改写部分代码，阅读成功才记录到list.db，不成功退出再换一个（百灵除外）。

**Comment by Ivan-cn** [comment]
> 改好记的发我一份
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ivan-cn"<notifications@github.com&gt;; 发送时间: 2020年10月30日(星期五) 上午10:23 收件人: "lolisaikou/LazyStudy"<LazyStudy@noreply.github.com&gt;; 抄送: "55142484"<zhangop9@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [lolisaikou/LazyStudy] //挑战答题引入Ivan-cn的处理方式，将随机点击的正确答案写入题库 (#99) 我改了部分代码，将点击失败和随机点击合并在一起，localTiku为全局变量，如果为true才更新。 主要代码： let hasClicked = false; let listArray = className("ListView").findOnce().children();//题目选项列表 console.info("答案：" + answer); //如果找到答案 if (answer.length != 0)//如果到答案 { var clickAns = ""; listArray.forEach(item =&gt; { var listDescStr = item.child(0).child(1).text(); if (listDescStr == answer) { clickAns = answer; //显示 对号 var b = item.child(0).bounds(); var tipsWindow = drawfloaty(b.left, b.top); //随机时长点击 delay(0.3); //点击 item.child(0).click(); hasClicked = true; delay(0.3); //消失 对号 tipsWindow.close(); } }); } if (!hasClicked || answer.length == 0){//如果没有点击成功，或找不到题目 if (!hasClicked){ console.error("未能成功点击，随机点击"); } if (answer.length == 0) { console.error("未找到答案，随机点击"); } delay(0.3); let i = random(0, listArray.length - 1); listArray[i].child(0).click();//随意点击一个答案 ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案 console.log("随机点击:"+ClickAnswer); console.log("------------------------"); //随机点击答案正确，更新到本地题库tiku表 delay(0.5);//等待0.5秒，是否出现X if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" + "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists()) { if (localTiku) { console.log("更新本地题库答案..."); var ansTiku = getAnswer(question, 'tiku'); if (ansTiku == "") { //题库为空则插入正确答案 var sql = "INSERT INTO tiku VALUES ('" + question + "','" + ClickAnswer + "','')"; } else { //更新题库答案 var sql = "UPDATE tiku SET answer='" + ClickAnswer + "' WHERE question LIKE '" + question + "'"; } insertOrUpdate(sql); delay(0.5); } } } } 能做一个没有微信推送的版本吗？ 那我在配置文件加个是否推送的开关就行，目前还在完善文章和视频阅读的环节，改写部分代码，阅读成功才记录到list.db，不成功退出再换一个（百灵除外）。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

更新了项目

**Comment by nishenge** [comment]
能放一个成品出来么

**Comment by ID-JRL** [comment]
> > 改好记的发我一份
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Ivan-cn"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年10月30日(星期五) 上午10:23 收件人: "lolisaikou/LazyStudy"<[LazyStudy@noreply.github.com](mailto:LazyStudy@noreply.github.com)>; 抄送: "55142484"<[zhangop9@qq.com](mailto:zhangop9@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [lolisaikou/LazyStudy] //挑战答题引入Ivan-cn的处理方式，将随机点击的正确答案写入题库 (#99) 我改了部分代码，将点击失败和随机点击合并在一起，localTiku为全局变量，如果为true才更新。 主要代码： let hasClicked = false; let listArray = className("ListView").findOnce().children();//题目选项列表 console.info("答案：" + answer); //如果找到答案 if (answer.length != 0)//如果到答案 { var clickAns = ""; listArray.forEach(item => { var listDescStr = item.child(0).child(1).text(); if (listDescStr == answer) { clickAns = answer; //显示 对号 var b = item.child(0).bounds(); var tipsWindow = drawfloaty(b.left, b.top); //随机时长点击 delay(0.3); //点击 item.child(0).click(); hasClicked = true; delay(0.3); //消失 对号 tipsWindow.close(); } }); } if (!hasClicked || answer.length == 0){//如果没有点击成功，或找不到题目 if (!hasClicked){ console.error("未能成功点击，随机点击"); } if (answer.length == 0) { console.error("未找到答案，随机点击"); } delay(0.3); let i = random(0, listArray.length - 1); listArray[i].child(0).click();//随意点击一个答案 ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案 console.log("随机点击:"+ClickAnswer); console.log("------------------------"); //随机点击答案正确，更新到本地题库tiku表 delay(0.5);//等待0.5秒，是否出现X if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" + "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists()) { if (localTiku) { console.log("更新本地题库答案..."); var ansTiku = getAnswer(question, 'tiku'); if (ansTiku == "") { //题库为空则插入正确答案 var sql = "INSERT INTO tiku VALUES ('" + question + "','" + ClickAnswer + "','')"; } else { //更新题库答案 var sql = "UPDATE tiku SET answer='" + ClickAnswer + "' WHERE question LIKE '" + question + "'"; } insertOrUpdate(sql); delay(0.5); } } } } 能做一个没有微信推送的版本吗？ 那我在配置文件加个是否推送的开关就行，目前还在完善文章和视频阅读的环节，改写部分代码，阅读成功才记录到list.db，不成功退出再换一个（百灵除外）。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 更新了项目

又不好使了 请大佬更新

**Comment by liangchaohua** [comment]
> > 功点击，随机点击"); } if (answer.length == 0) { console.error("未找到答案，随机点击"); } delay(0.3); let i = random(0, listArray.length - 1); listArray[i].child(0).click();//随意点击一个答案 ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案 console.log("随机点击:"+ClickAnswer); console.log("------------------------"); //随机点击答案正确，更新到本地题库tiku表 delay(0.5);//等待0.5秒，是否出现X if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" + "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists()) { if (localTiku) { console.log("更新本地题库答案..."); var ansTiku = getAnswer(question, 'tiku'); if (ansTiku == "") { //题库为空则插入正确答案 var sql = "INSERT INTO tiku VALUES ('" + question + "','" + ClickAnswer + "','')"; } else { //更新题库答案 var sql = "UPDATE tiku SET answer='" + ClickAnswer + "' WHERE question LIKE '" + question + "'"; } insertOrUpdate(sql); delay(0.5); } } } } 能做一个没有微信推送的版本吗？ 那我在配置文件加个是否推送的开关就行，目前还在完善文章和视频阅读的环节，改写部分代码，阅读成功才记录到list.db，不成功退出再换一个（百灵除外）。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 更新了项目

您好，你2.8版本。。一键满分版。。下载了用不了 。。好像文件提示没有某文件，之前用你的2.7.1.2版本很好用。   :（

**Comment by LIDH-byte** [comment]
> > 改好记的发我一份
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Ivan-cn"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年10月30日(星期五) 上午10:23 收件人: "lolisaikou/LazyStudy"<[LazyStudy@noreply.github.com](mailto:LazyStudy@noreply.github.com)>; 抄送: "55142484"<[zhangop9@qq.com](mailto:zhangop9@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [lolisaikou/LazyStudy] //挑战答题引入Ivan-cn的处理方式，将随机点击的正确答案写入题库 (#99) 我改了部分代码，将点击失败和随机点击合并在一起，localTiku为全局变量，如果为true才更新。 主要代码： let hasClicked = false; let listArray = className("ListView").findOnce().children();//题目选项列表 console.info("答案：" + answer); //如果找到答案 if (answer.length != 0)//如果到答案 { var clickAns = ""; listArray.forEach(item => { var listDescStr = item.child(0).child(1).text(); if (listDescStr == answer) { clickAns = answer; //显示 对号 var b = item.child(0).bounds(); var tipsWindow = drawfloaty(b.left, b.top); //随机时长点击 delay(0.3); //点击 item.child(0).click(); hasClicked = true; delay(0.3); //消失 对号 tipsWindow.close(); } }); } if (!hasClicked || answer.length == 0){//如果没有点击成功，或找不到题目 if (!hasClicked){ console.error("未能成功点击，随机点击"); } if (answer.length == 0) { console.error("未找到答案，随机点击"); } delay(0.3); let i = random(0, listArray.length - 1); listArray[i].child(0).click();//随意点击一个答案 ClickAnswer = listArray[i].child(0).child(1).text();;//记录已点击答案 console.log("随机点击:"+ClickAnswer); console.log("------------------------"); //随机点击答案正确，更新到本地题库tiku表 delay(0.5);//等待0.5秒，是否出现X if (!text("v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw" + "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC").exists()) { if (localTiku) { console.log("更新本地题库答案..."); var ansTiku = getAnswer(question, 'tiku'); if (ansTiku == "") { //题库为空则插入正确答案 var sql = "INSERT INTO tiku VALUES ('" + question + "','" + ClickAnswer + "','')"; } else { //更新题库答案 var sql = "UPDATE tiku SET answer='" + ClickAnswer + "' WHERE question LIKE '" + question + "'"; } insertOrUpdate(sql); delay(0.5); } } } } 能做一个没有微信推送的版本吗？ 那我在配置文件加个是否推送的开关就行，目前还在完善文章和视频阅读的环节，改写部分代码，阅读成功才记录到list.db，不成功退出再换一个（百灵除外）。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 更新了项目

大佬，2.8版本怎么删除了，能私我一份学习一下专项答题和每周答题的代码吗？
